/* =========================================================
   CARRETEO · cards.js
   TODO el contenido del juego vive aquí. Ninguna lógica.
   Para agregar una carta basta con sumar un string al `deck`
   del modo que corresponda.

   Formato: "[I]tipoN|texto"
     [I]   intensidad 1=suave 2=medio 3=picante.
           Si se omite, la carta hereda el `lvl` del modo.
     tipo  r=reto p=pregunta yn=yo nunca rg=regla vt=votación
           vs=duelo mm=mímica tm=contrarreloj dd=dado sh=shot
           cc=cultura chupística tr=reparte aq=agua
           pc=premio o castigo
     N     rondas (rg) o segundos (tm)
     texto {j} y {j2} se reemplazan por jugadores.
           § separa partes: pregunta§respuesta · reto§premio§castigo
   ========================================================= */

/* ---------- tipos de carta ---------- */
const TYPES={
  r:{l:'Reto'}, p:{l:'Pregunta'}, yn:{l:'Yo nunca'}, rg:{l:'Regla nueva'}, vt:{l:'Votación'}, vs:{l:'Duelo'}, mm:{l:'Mímica'}, tm:{l:'Contrarreloj'}, dd:{l:'Dado'}, sh:{l:'Shot'}, cc:{l:'Cultura chupística'}, tr:{l:'Reparte'}, aq:{l:'Hidrátate 💧'}
};

/* ---------- modos de cartas ---------- */
const MODES=[
{id:'previa',nm:'Previa',em:'🥤',c:'#8b6cff',ds:'Para romper el hielo sin sustos.',lvl:1,deck:[
`r|{j}, imita el saludo característico de alguien del grupo. Si adivinan a quién, todos toman 1; si no, tomas 2.`,
`p|{j}, ¿cuál fue tu primera impresión de {j2}? Sé honesto y toma 1 por los nervios.`,
`yn|Yo nunca me he quedado dormido en una fiesta. Quien lo hizo, toma 2.`,
`vt|Voten: ¿quién del grupo llegaría tarde a su propia boda? El elegido toma 2.`,
`r|{j}, cuenta tu mejor dato inútil. Si a nadie le sorprende, tomas 2.`,
`cc|Marcas de bebidas. {j} empieza, sigan en ronda. El que falla o repite toma 3.`,
`rg3|Prohibido decir "sí". Quien lo diga toma 1.`,
`tr|{j}, reparte 3 sorbos entre quienes quieras.`,
`p|{j}, ¿playa o montaña? Los que opinen distinto a ti toman 1.`,
`r|Todos cambien de asiento ya. El último en sentarse toma 2.`,
`tm20|{j}, nombra 5 países que empiecen con la misma letra antes del pitido o toma 3.`,
`yn|Yo nunca he stalkeado a un ex. Quien sí, toma 2.`,
`vs|{j} vs {j2}: piedra, papel o tijera al mejor de 3. El perdedor toma 2.`,
`dd|{j}, lanza el dado y toma esa cantidad de sorbos.`,
`aq|Pausa saludable: todos toman un buen sorbo de AGUA. Tu yo de mañana lo agradece.`,
`p|{j}, ¿qué canción te pone de buen humor sí o sí? Ponla, y todos toman 1 al ritmo.`,
`r|{j}, preséntate al grupo con el nombre de tu mascota o uno inventado. Si te ríes al decirlo, toma 1.`,
`p|{j}, ¿cómo llegaste a esta previa: te invitaron, te colaste o eres de la casa? Si te enteraste el mismo día, toma 1.`,
`yn|Yo nunca he llegado a una junta sin saber bien de quién era la casa. Quien sí, toma 2.`,
`vt|Voten: ¿quién trae la mejor energía a esta previa? Esa persona reparte 2 sorbos.`,
`vs|{j} vs {j2}: digan por turnos algo que creen que el otro nunca ha hecho. El primero que acierte reparte 2 sorbos; el otro toma 2.`,
`r|{j}, ponle un apodo nuevo a {j2} que se use el resto de la noche. Si a {j2} no le gusta, ambos toman 1.`,
`mm|{j}, actúa "llegar tarde a la previa con una excusa penca". Si adivinan, todos toman 1; si no, tomas 2.`,
`dd|{j}, lanza el dado: di esa cantidad de cosas verdaderas sobre ti, sin repetir. Si te quedas pegado, toma 2.`,
`p|{j}, ¿qué trajiste a la previa? Si llegaste con las manos vacías, toma 2.`,
`tr|{j}, reparte 2 sorbos entre los que conociste hoy. Si ya los conocías a todos, tomas 2 tú.`,
`r|{j}, arranca la cadena: cada uno repite los nombres anteriores y suma el suyo con un gusto raro. El que se enreda toma 2.`,
`yn|Yo nunca me he cambiado de ropa después de ver cómo iban vestidos los demás. Quien sí, toma 1.`,
`cc|Ronda de piqueos de previa: {j} arranca y siguen en cadena. El que repite o se queda callado toma 3.`,
`rg2|{j} pone la regla: antes de tomar, cada uno dice su nombre en voz alta. Quien lo olvide toma 1.`,
`vt|Voten: ¿quién va a ser el último en irse hoy? Esa persona reparte 2 sorbos.`,
`pc|{j} y {j2}, encuentren tres cosas que tengan en común en 20 segundos§ambos reparten 2 sorbos§ambos toman 2 sorbos`]},
{id:'locura',nm:'Locura',em:'🤪',c:'#ff3d7f',ds:'Caos puro. Nadie sale igual.',lvl:2,deck:[
`r|{j}, habla como robot hasta tu próximo turno o toma 3.`,
`r|El último en tocar algo de color rojo toma 3.`,
`rg4|{j} es "Su Majestad". Quien le hable sin decirle Majestad toma 2.`,
`tm15|Papa caliente: pasen el celular en círculo. Quien lo tenga cuando suene, toma 3.`,
`r|{j}, muéstrale a {j2} la última foto de tu galería o toma 4.`,
`vs|{j} vs {j2}: duelo de miradas. El primero en reír o parpadear toma 3.`,
`r|{j}, baila 15 segundos sin música. El grupo decide: aprobado (todos toman 1) o reprobado (tomas 3).`,
`sh|{j}, el destino te eligió: shot o cuenta tu momento más vergonzoso.`,
`tr|{j}, elige a tu socio de fechorías: cada vez que tú tomes, esa persona toma contigo por 3 rondas.`,
`r|Todos hablen en susurros hasta la próxima carta. Quien grite, toma 2.`,
`dd|{j}, lanza el dado: si sale par repartes esa cantidad, si sale impar la tomas tú.`,
`r|{j}, intercambia una prenda visible (chaqueta, gorro, lentes) con {j2} o ambos toman 2.`,
`yn|Yo nunca me he ido de una fiesta sin despedirme. Los fantasmas 👻 toman 2.`,
`mm|{j}, actúa "gallina en patineta". Si nadie adivina en 30 segundos, tomas 3.`,
`r|Grito grupal en 3, 2, 1… El más tímido toma 2.`,
`r|{j}, eres el eco del grupo: repite en voz alta la última palabra de cada frase ajena hasta tu próximo turno. Si fallas, toma 2.`,
`rg3|Nueva regla: prohibido señalar con el dedo, solo se señala con el codo. Quien use el dedo toma 1.`,
`r|{j}, agarra el objeto más cercano y véndelo al grupo como si fuera lo mejor del mundo, 15 segundos. Si nadie aplaude, toma 3.`,
`tm10|{j}, inventa un idioma al instante y di una frase completa en él antes del pitido. Si te trabas o hablas español, toma 3.`,
`vs|{j} vs {j2}: cuenten lo que hicieron hoy con un acento inventado. El grupo elige al menos convincente y ese toma 3.`,
`dd|{j}, lanza el dado: ese número son los ruidos raros distintos que tienes que hacer seguidos. Si repites uno, toma 2.`,
`r|{j}, narra en voz alta lo que hace el grupo por 20 segundos, tipo documental de animales. Si nadie se ríe, toma 2.`,
`mm|{j}, actúa "pulpo tratando de abrir una puerta". Si nadie adivina en 30 segundos, tomas 3.`,
`rg3|Nueva regla: todo brindis termina con el grito de guerra que invente {j} ahora. Quien lo olvide toma 1.`,
`r|{j} y {j2}: inventen un saludo secreto de 5 movimientos en 20 segundos, o ambos toman 2 y se saltan el reto.`,
`tr|{j}, reparte 3 sorbos: uno a la mejor risa, uno al que más se mueve y uno al más caótico de la noche.`,
`p|{j}, si mañana despiertas convertido en un animal, ¿cuál sería y qué harías primero? Si dudas más de 5 segundos, toma 2.`,
`yn|Yo nunca he hecho algo ridículo solo porque el grupo me estaba grabando. Quien sí, toma 2.`,
`vt|Voten: ¿quién tiene la risa más contagiosa? Esa persona se ríe a la fuerza 5 segundos y todos toman 1.`,
`pc|{j}, arma una torre con 5 cosas de la mesa que no se rompan y que aguante 5 segundos§reparte 3 sorbos§toma 3 sorbos`,
`cc|Ronda de nombres de bandas falsas: {j} arranca y siguen en cadena. El que repite o duda toma 2.`]},
{id:'bar',nm:'Bar',em:'🍸',c:'#ffb24d',ds:'Rápidas y directas, para la salida.',lvl:1,deck:[
`r|{j}, brinda con un discurso de 10 segundos por algo absurdo. Todos toman 1.`,
`vt|Voten: ¿quién sobreviviría menos a una noche sin celular? Toma 2.`,
`r|{j}, cuenta un chiste ya. Si nadie ríe, tomas 2.`,
`cc|Cócteles o tragos. {j} arranca. El que repite o falla toma 3.`,
`p|{j}, ¿cuál es tu "pedido de siempre"? Quien pediría lo mismo toma 1 contigo.`,
`r|El último en chocar su vaso con todos toma 2.`,
`tm20|{j}, nombra 6 bares, antros o discos antes del pitido o toma 3.`,
`yn|Yo nunca he fingido conocer una canción en el karaoke. Toma 2.`,
`vs|{j} vs {j2}: quién aguanta más sin usar las manos para nada. El primero en usarlas toma 2.`,
`rg3|Solo se puede beber con la mano menos hábil. Infractores toman 1 extra.`,
`tr|{j}, invita 2 sorbos a la persona mejor vestida del grupo.`,
`r|{j}, logra que alguien te diga "salud" sin pedirlo directamente, o toma 2.`,
`dd|{j}, dado al aire: del 1 al 3 tomas tú, del 4 al 6 eliges quién.`,
`aq|Ronda de agua para todo el bar. Hidratarse también es de valientes.`,
`mm|{j}, actúa "pedirle la cuenta a un mozo desde el otro lado del local", sin hablar. Si nadie adivina, tomas 2.`,
`p|{j}, ¿cuál es la propina más rara que has dejado o recibido? Cuenta o toma 2.`,
`yn|Yo nunca he pedido algo solo porque se veía bacán en la mesa de al lado. Quien sí, toma 2.`,
`vt|Voten: ¿quién termina siempre organizando cómo se divide la cuenta? Esa persona reparte 2 sorbos.`,
`r|{j}, invéntale un nombre pomposo a lo que estés tomando, aunque sea agua, y preséntalo a la mesa. Todos brindan y toman 1.`,
`cc|Ronda de motivos para brindar, uno distinto cada uno. {j} arranca; el que repite o duda toma 3.`,
`vs|{j} vs {j2}: cada uno cuenta en 15 segundos su peor salida a un bar. El grupo elige la más penca y esa persona toma 2.`,
`tm15|{j}, nombra 5 canciones que dejarían a esta mesa hasta el cierre, antes del pitido, o toma 2.`,
`p|{j}, ¿qué canción te haría salir arrancando de este local? Si a alguien le encanta, esa persona toma 2.`,
`dd|{j}, lanza el dado: ese número son las palabras exactas que puede tener tu próxima frase. Si te pasas, toma 2.`,
`p|{j}, ¿qué pedirías ahora mismo si supieras que no te lo van a cobrar? Responde rápido o toma 2.`,
`tr|{j}, reparte 2 sorbos a quien hizo el pedido más raro de la mesa hoy.`,
`rg2|Nueva regla de mesa: cada vez que alguien pide algo, todos responden "buena elección". Quien no lo diga toma 1.`,
`vt|Voten: ¿quién sería el mejor mesero de esta mesa? Esa persona reparte 2 sorbos como propina.`,
`sh|{j}, shot o cuenta cuál es el trago más feo que has probado en tu vida.`,
`pc|{j}, adivina qué está tomando {j2} sin mirar su vaso§repartes 2 sorbos§tomas 2 sorbos`]},
{id:'coqueto',nm:'Coqueto',em:'😏',c:'#ff6ea9',ds:'Sube la temperatura… con estilo.',lvl:2,deck:[
`p|{j}, ¿cuál es tu "green flag" favorita en una persona? Quien la tenga, toma 1 con orgullo.`,
`r|{j}, lánzale tu mejor piropo (respetuoso) a {j2}. Si se sonroja, toma 1; si no, tomas tú 2.`,
`yn|Yo nunca he mandado un mensaje coqueto que quedó en visto. F. Toma 2.`,
`vt|Voten: ¿quién tiene la mejor sonrisa del grupo? El ganador reparte 3 sorbos.`,
`rg2|{j}, guiña un ojo a {j2} cada vez que {j2} hable.`,
`p|{j}, describe tu cita ideal en 10 palabras exactas o toma 2.`,
`vs|{j} vs {j2}: duelo de miradas intensas estilo telenovela. Quien ría primero toma 2.`,
`r|{j}, di el nombre de {j2} con tu voz más seductora. Si el jurado da menos de 7/10, tomas 2.`,
`yn|Yo nunca he ensayado una conversación antes de tenerla. Toma 1, estratega.`,
`p|{j}, tu primer beso: ¿historia romántica o desastre? Cuéntala o toma 3.`,
`rg3|Prohibido decir "amor", "lindo", "linda" o "bebé". Toma 1 por infracción.`,
`r|{j}, envía un "hola 😏" a tu último match o crush… o toma 3 y guarda el misterio.`,
`tr|{j}, regala 2 sorbos a quien te caiga mejor hoy. Sin explicaciones.`,
`p|{j}, ¿qué canción le dedicarías a alguien presente? No digas a quién. Todos toman 1 de intriga.`,
`p|{j}, ¿cuál es tu mejor línea para partir conversación con alguien que te gusta? Dila en serio, sin reírte, o toma 2.`,
`vt|Voten: ¿quién se pone más nervioso cuando le tiran los perros? El elegido toma 2 y lo niega igual.`,
`yn|Yo nunca le he pedido el número a alguien cara a cara en un carrete. Quien sí, toma 2 con estilo.`,
`tm20|{j}, tienes 20 segundos para hacer reír a {j2} sin contar un chiste. Si lo logras, {j2} toma 2; si no, tomas 3.`,
`rg2|{j} pone la regla: por 2 rondas, quien reciba un cumplido debe responder "lo sé" con total seguridad. Quien se ría, toma 1.`,
`p|{j}, si mandaras un mensaje para reconquistar a alguien, ¿qué diría? Léelo tal cual en voz alta o toma 2.`,
`tr|{j}, reparte 3 sorbos entre quienes crees que se enamoran más rápido. Si te incluyes, uno de esos es tuyo.`,
`r|{j}, invita a bailar a {j2} 10 segundos con toda la elegancia posible, o ambos toman 2. Si el grupo aplaude, toman 1.`,
`p|{j}, ¿cuál es la mentirita blanca más grande que has dicho para impresionar a alguien que te gustaba? Cuéntala o toma 3.`,
`vs|{j} vs {j2}: 15 segundos cada uno para convencer al grupo de por qué sería la mejor cita. El menos convincente toma 2.`,
`yn|Yo nunca he cambiado de ruta a propósito para cruzarme "por casualidad" con alguien que me gustaba. Quien sí, toma 2.`,
`pc|{j}, dedícale a {j2} un piropo que compare su encanto con un electrodoméstico§Si el grupo ríe, reparte 2 sorbos§Si nadie ríe, toma 3`,
`p|{j}, ¿qué gesto mínimo de otra persona te derrite al toque? Sé específico o toma 2. Quien lo haga ahora, toma 1.`,
`r|{j}, actúa cómo te acercarías a {j2} si fuera la primera vez que se ven en un bar. Si el grupo aplaude, repartes 2; si no, tomas 2.`,
`vt|{j} abre la votación: ¿quién sería el mejor casamentero del grupo? El ganador reparte 2 sorbos con orgullo.`,
`dd|{j}, lanza el dado: con 1 o 2 cuenta una cita desastrosa, con 3 o 4 una que la rompió, con 5 o 6 toma 3.`]},
{id:'trivia',nm:'Trivia',em:'🧠',c:'#59c2ff',ds:'Fallas, tomas. Simple.',lvl:1,deck:[
`p|¿Cuál es el río más largo del mundo?§El Amazonas, según las mediciones más recientes (el Nilo pelea el título). Si fallaste, toma 2.`,
`p|¿En qué año llegó el ser humano a la Luna?§1969. Fallo = 2 sorbos.`,
`p|¿Cuántos corazones tiene un pulpo?§Tres. Fallo = 2 sorbos.`,
`p|¿Cuál es la capital de Australia?§Canberra (no, no es Sídney). Fallo = 2 sorbos.`,
`p|¿Qué planeta es el más caliente del sistema solar?§Venus. Fallo = 2 sorbos.`,
`p|¿Cuántos huesos tiene el cuerpo humano adulto?§206. Fallo = 2 sorbos.`,
`p|¿Quién pintó "La noche estrellada"?§Vincent van Gogh. Fallo = 2 sorbos.`,
`p|¿Cuál es el país más poblado del mundo?§India (superó a China en 2023). Fallo = 2 sorbos.`,
`p|¿Cuál es el animal más rápido del planeta?§El halcón peregrino, en picada. Fallo = 2 sorbos.`,
`p|¿Cuántos minutos tiene un día completo?§1.440 minutos. Fallo = 2 sorbos.`,
`p|¿Cuál es el idioma con más hablantes nativos?§El chino mandarín. Fallo = 2 sorbos.`,
`p|¿Qué gas es el más abundante en el aire que respiramos?§El nitrógeno (~78%). Fallo = 2 sorbos.`,
`p|¿Cuántas cuerdas tiene una guitarra clásica?§Seis. Fallo = 2 sorbos.`,
`p|¿En qué continente está Egipto?§África (aunque el Sinaí es Asia, tramposos). Fallo = 2 sorbos.`,
`p|¿Cuál es el océano más grande del mundo?§El Pacífico. Si fallaste, toma 2.`,
`p|¿Cuál es el hueso más largo del cuerpo humano?§El fémur. Si fallaste, toma 2.`,
`p|¿En qué año cayó el Muro de Berlín?§En 1989. Si fallaste, toma 2.`,
`p|¿Cuál es la moneda oficial de Japón?§El yen. Si fallaste, toma 2.`,
`p|¿Qué elemento químico corresponde al símbolo "Fe"?§El hierro. Si fallaste, toma 2.`,
`p|¿Qué país tiene forma de bota en el mapa?§Italia. Si fallaste, toma 2.`,
`p|¿Cuántos jugadores de cada equipo hay en la cancha en un partido de fútbol?§Once, contando al arquero. Si fallaste, toma 2.`,
`p|¿Cuál es el único metal que es líquido a temperatura ambiente?§El mercurio. Si fallaste, toma 2.`,
`p|¿Quién escribió "Cien años de soledad"?§Gabriel García Márquez. Si fallaste, toma 2.`,
`p|¿Cuál es la capital de Canadá?§Ottawa, allá en Ontario. Si fallaste, toma 2.`,
`p|¿Cuántos lados tiene un hexágono?§Seis. Si fallaste, toma 2.`,
`p|¿Cuál es el órgano más grande del cuerpo humano?§La piel. Si fallaste, toma 2.`,
`p|¿En qué país está Machu Picchu?§En Perú. Si fallaste, toma 2.`,
`p|¿A cuántos grados Celsius hierve el agua a nivel del mar?§A 100 grados. Si fallaste, toma 2.`,
`p|¿Cuál es el desierto no polar más árido del mundo?§El de Atacama, aquí mismo en Chile. Si fallaste, toma 2.`,
`p|¿Cuál es el mamífero más grande del mundo?§La ballena azul. Si fallaste, toma 2.`]},
{id:'parejas',nm:'Parejas',em:'💘',c:'#ff5470',ds:'Para dos. Modo cita.',min:2,lvl:2,deck:[
`p|{j}, ¿qué fue lo primero que te atrajo de {j2}? Con detalles o tomas 2.`,
`r|Mírense a los ojos 30 segundos sin hablar. Quien ría primero toma 2.`,
`p|{j}, ¿cuál ha sido su mejor cita hasta ahora y por qué?`,
`r|{j}, dale un beso a {j2} donde tú elijas (con respeto 😌) o ambos toman 1.`,
`yn|Yo nunca he revisado el horóscopo de mi pareja. Quien sí, toma 1.`,
`p|{j2}, ¿qué manía tuya crees que {j} tolera con amor? Si aciertas, ambos toman 1 de premio.`,
`r|Planeen en 60 segundos su próxima escapada soñada. Si no se ponen de acuerdo, ambos toman 2.`,
`p|{j}, ¿qué canción es "la de ustedes"? Si no coinciden, ambos toman 2.`,
`r|{j}, imita a {j2} en una discusión típica. Si {j2} se ríe, toma 2; si se ofende, tomas tú 2.`,
`p|{j2}, di 3 cosas que admiras de {j}. Si dices menos de 3, tomas 3.`,
`r|Abrazo de 10 segundos, obligatorio y sin quejas. Después ambos toman 1 por cursis.`,
`p|{j}, ¿qué aprendiste de tu peor relación pasada? Comparte o toma 2.`,
`vs|Duelo: ¿quién conoce mejor al otro? Cada uno hace una pregunta; quien falle toma 2.`,
`tr|{j}, decide: ambos toman 2 juntos, o nadie toma y se deben un favor.`,
`p|{j}, ¿qué regalo le hiciste a {j2} que claramente no le gustó? Confiesa o ambos toman 2.`,
`p|{j}, ¿cuál es la pelea más tonta que han tenido? Que {j2} confirme tu versión o ambos toman 2.`,
`p|{j}, ¿qué costumbre de {j2} te chocaba al principio y ahora te encanta? Cuenta con ejemplo o toma 2.`,
`p|{j2}, ¿en qué momento supiste que {j} te gustaba en serio? Con fecha aproximada o toma 2.`,
`p|{j}, ¿cuál es el apodo más vergonzoso que le has puesto a {j2}? Dilo fuerte y claro o toma 3.`,
`r|{j}, cuéntale a {j2} algo que hizo por ti y que nunca le agradeciste bien. Después ambos toman 1.`,
`r|{j} y {j2}: recreen su primera conversación, palabra por palabra. Si no se acuerdan, ambos toman 2.`,
`r|{j}, con los ojos cerrados, describe qué ropa trae puesta {j2} hoy. Si aciertas todo, {j2} toma 1; si fallas, tomas 2.`,
`r|{j} y {j2}: sin mirarse, digan a la vez quién dijo "te quiero" primero. Si no coinciden, ambos toman 2.`,
`yn|Yo nunca he dicho "no pasa nada" cuando claramente sí pasaba algo. Quien sí, toma 2.`,
`yn|Yo nunca he fingido que me encantaba un plan de mi pareja solo por amor. Toma 1, mártir del cariño.`,
`vs|{j} vs {j2}: adivinen en una frase qué está pensando el otro ahora mismo. Quien quede más lejos toma 2.`,
`tr|{j}, reparte 3 sorbos entre tú y {j2} como quieras. Justifica el reparto o toma 1 extra.`,
`rg2|Por 2 rondas, {j} y {j2} hablan siempre en plural: todo es "nosotros". Quien diga "yo", toma 1.`,
`mm|{j}, actúa sin palabras el mejor panorama que han hecho juntos. Si {j2} adivina cuál es, ambos toman 1; si no, tomas 2.`,
`pc|{j}, en 20 segundos dile a {j2} tres razones para seguir juntos, sin repetir ninguna§Ambos toman 1 de brindis§Si te trabas, tomas 3`]},
{id:'after',nm:'After',em:'🌙',c:'#c084fc',ds:'Solo para valientes de madrugada.',lvl:3,deck:[
`sh|{j}, es tarde para arrepentirse: shot o confiesa a qué hora querías irte en realidad.`,
`p|{j}, ¿cuál es el mensaje del que más te arrepientes haber enviado? Cuenta o toma 4.`,
`yn|Yo nunca he llorado en una fiesta. Los sensibles toman 2, con orgullo.`,
`r|{j}, llama a tu mejor amigo que no está aquí y dile que lo quieres. O toma 4.`,
`vt|Voten: ¿quién está más cerca de quedarse dormido? Toma 3 para despertar.`,
`r|{j}: {j2} dice un número al azar y tú muestras esa foto de tu galería, o tomas 4.`,
`p|{j}, ¿qué harías si supieras que nadie te va a juzgar? Responde o toma 3.`,
`rg4|Modo confesionario: quien haga una pregunta debe responderla también. Infracción: 2 sorbos.`,
`sh|Quien no haya dicho nada vergonzoso hoy, toma un shot… o confiesa algo ya.`,
`r|{j}, intercambia celulares (bloqueados 😉) con {j2} por una ronda. Quien se niegue toma 3.`,
`yn|Yo nunca he dicho "esta es la última" y pedí otra. Todos sabemos quiénes son: toman 3.`,
`p|{j}, ¿a quién del grupo le confiarías un secreto grave? Señálalo; esa persona toma 1 de honor.`,
`tm25|{j}, convence al grupo de por qué la noche NO debe terminar. Si no aplauden, tomas 3.`,
`aq|Check de realidad: agua para todos. La mejor decisión de la noche.`,
`tr|{j}, reparte 5 sorbos. Con gran poder viene gran resaca.`,
`p|{j}, ¿cuál es el secreto que llevas años guardando y que ya no te sirve de nada? Suéltalo o toma 3 sorbos.`,
`yn|Yo nunca he jurado que ya superé a alguien mientras seguía revisando sus historias. Quien sí, toma 2 sorbos.`,
`r|{j}, dile a {j2} en la cara una verdad que nunca le has dicho. Si te achicas, tomas 3 sorbos.`,
`sh|{j}, shot de las 4 AM: te lo tomas o le regalas 3 sorbos al que más ha hablado esta noche.`,
`vt|Voten: ¿quién va a mandar esta madrugada el mensaje que mañana quisiera borrar? El más votado toma 3 sorbos.`,
`rg4|Se acabaron las bromas para escapar: quien conteste una pregunta con un chiste en vez de la verdad toma 2 sorbos.`,
`tm20|{j}, antes del pitido di 3 cosas que te dan miedo de verdad, nada de chistes. Si no llegas, tomas 3 sorbos.`,
`dd|{j}, lanza el dado: del 1 al 3 cuentas un arrepentimiento de este año; del 4 al 6 tomas 3 sorbos y te lo guardas.`,
`tr|{j}, reparte 4 sorbos entre los que juraron irse temprano y siguen aquí, máximo 1 por persona.`,
`pc|{j}, cuenta la razón real por la que terminó tu última relación§El grupo brinda por tu honestidad y todos toman 1 sorbo§Toma 3 sorbos`,
`vs|{j} vs {j2}: cada uno dice dos confesiones y una mentira. El que no cache cuál era la mentira toma 3 sorbos.`,
`cc|Categoría: cosas de las que uno se arrepiente recién al otro día. {j} parte y siguen en ronda. Quien dude o repita toma 3 sorbos.`,
`p|{j}, ¿a quién de los presentes le debes una disculpa de verdad? Dísela ahora o toma 3 sorbos.`,
`p|{j}, de todo lo que subiste hoy a tus historias, ¿cuánto era para que lo viera una sola persona? Confiesa o toma 2 sorbos.`,
`r|{j}, di en voz alta el nombre de la persona en la que estabas pensando cuando salió esta carta, o toma 3 sorbos.`,
`r|Ronda de las 4 AM: cada uno dice en una palabra cómo se siente de verdad. El que mienta toma 2 sorbos.`]},
{id:'mimica',nm:'Mímica',em:'🎭',c:'#ffd166',ds:'Actúa sin hablar. 30 seg: si no adivinan, el actor toma 3; si adivinan, el resto toma 1.',lvl:1,deck:[
`mm|{j}, actúa: influencer grabando un unboxing.`,
`mm|{j}, actúa: gato que tiró un vaso y no se arrepiente.`,
`mm|{j}, actúa: persona buscando señal de wifi en medio del campo.`,
`mm|{j}, actúa: abuela aprendiendo a usar TikTok.`,
`mm|{j}, actúa: superhéroe con dolor de espalda.`,
`mm|{j}, actúa: cajero de supermercado un lunes a primera hora.`,
`mm|{j}, actúa: turista perdido preguntando direcciones.`,
`mm|{j}, actúa: chef furioso probando una sopa horrible.`,
`mm|{j}, actúa: fan conociendo a su ídolo.`,
`mm|{j}, actúa: robot bailando reguetón.`,
`mm|{j}, actúa: profesor de yoga estresado.`,
`mm|{j}, actúa: vampiro vegetariano.`,
`mm|{j}, actúa: árbitro cobrando penal en la final.`,
`mm|{j}, actúa: persona que pisó una pieza de Lego descalza.`,
`mm|{j}, actúa: persona tratando de sacarle una foto a su perro que no se queda quieto.`,
`mm|{j}, actúa: persona sacando la basura en pijama que se topa con el vecino guapo.`,
`mm|{j}, actúa: alguien peleando con una botella cuya tapa no quiere salir.`,
`mm|{j}, actúa: pasajero de micro haciendo equilibrio sin agarrarse de nada.`,
`mm|{j}, actúa: vendedor ambulante ofreciendo maní confitado en el semáforo, sin que nadie lo pesque.`,
`mm|{j}, actúa: alguien bailando cueca solo en un asado familiar, con pañuelo imaginario.`,
`mm|{j}, actúa: persona que recuerda a mitad de camino que dejó la estufa prendida.`,
`mm|{j}, actúa: DJ de matrimonio que pinchó la canción equivocada y disimula.`,
`mm|{j}, actúa: alguien armando un mueble sin manual, con tornillos sobrando al final.`,
`mm|{j}, actúa: alguien persiguiendo una mosca por la cocina con un diario enrollado.`,
`mm|{j}, actúa: persona estacionando en paralelo con todo el barrio mirando.`,
`mm|{j}, actúa: alguien con las bolsas del supermercado rajándose en plena vereda.`,
`mm|{j}, actúa: persona comiendo un completo italiano gigante sin ensuciarse.`,
`mm|{j}, actúa: persona sentándose sobre una maleta para lograr cerrarla.`,
`mm|{j}, actúa: alguien fingiendo que entendió la explicación del mesero sobre el menú del día.`,
`mm|{j}, actúa: persona tratando de sacarse la selfie perfecta desde un ángulo imposible.`]},
{id:'hot',nm:'Hot',em:'🔥',c:'#ff2e63',ds:'Picante, confesional y con 👀.',lvl:3,deck:[
`p|{j}, ¿cuál es tu tipo? Descríbelo sin mirar a nadie… o mirando 👀. Toma 1 al terminar.`,
`yn|Yo nunca he tenido un sueño subido de tono con alguien de este grupo. Quien tome, no dice con quién 🤐.`,
`r|{j}, susurra algo al oído de {j2}. Si {j2} se ríe o sonroja, toma 2; si queda de piedra, tomas tú 2.`,
`vt|Voten: ¿quién es más coqueto sin darse cuenta? Toma 3.`,
`p|{j}, tu beso más memorable: ¿dónde fue? Ciudad y contexto, sin nombres. O toma 3.`,
`r|{j}, baila algo sensual 10 segundos o toma 3. El grupo aplaude sí o sí.`,
`yn|Yo nunca he vuelto con un ex sabiendo que era mala idea. Toma 3, campeón.`,
`p|{j}, del 1 al 10, ¿qué tan bien besas según tú? El grupo vota si te cree. Si no, tomas 2.`,
`r|{j} y {j2}: recreen la pose de portada de una novela romántica. Quien se niegue toma 3.`,
`p|{j}, ¿qué es más atractivo: inteligencia, humor o físico? Los que discrepen toman 1.`,
`rg3|Prohibido decir la palabra "sexy". Infracción: 2 sorbos.`,
`sh|{j}, shot o verdad: ¿te gusta alguien en este momento? Con sí o no basta.`,
`tr|{j}, regala 3 sorbos a la persona más guapa del grupo. Sin empates.`,
`yn|Yo nunca he coqueteado para conseguir algo gratis. Toma 2, estratega.`,
`p|{j}, ¿cuál ha sido el piropo más atrevido que te han dicho en la vida? Repítelo tal cual o toma 3.`,
`p|{j}, ¿cuál fue la señal más obvia de que alguien te estaba tirando los perros y no cachaste? Cuenta o toma 3.`,
`p|{j}, ¿qué red flag ignoraste a propósito porque la persona te gustaba demasiado? Cuéntala o toma 3.`,
`p|{j}, ¿cuál fue la mejor excusa que inventaste para quedarte más rato con alguien que te gustaba? Cuenta o toma 2.`,
`p|{j}, ¿cuánto te demoraste arreglándote la última vez que sabías que ibas a ver a alguien que te gusta? Confiesa o toma 2.`,
`yn|Yo nunca he estado en algo que no era pololeo ni amistad y no supe cómo explicarlo. Quien sí, toma 3.`,
`yn|Yo nunca he seguido a alguien en redes solo porque salía guapo en la foto de otra persona. Toma 2.`,
`r|{j}, hazle a {j2} la pregunta más atrevida que se te ocurra. {j2} responde solo sí o no, o toma 3.`,
`r|{j}, cuenta cómo fue la última vez que llegaste a tu casa de día con la ropa de ayer. Si prefieres el misterio, toma 3.`,
`r|{j}, confiesa qué buscaste en internet o en redes antes de una primera cita. Si no confiesas, toma 3.`,
`vt|{j} arranca la ronda: voten quién tiene el chat más picante escondido en el celular. Esa persona toma 3.`,
`vt|Voten: ¿quién tiene un ex secreto que nadie del grupo conoce? El más votado toma 2 y no da explicaciones.`,
`vs|{j} vs {j2}: cada uno confiesa algo que nunca había contado en este grupo. El grupo vota cuál fue más flojo; ese toma 3.`,
`sh|{j}, shot o confiesa: ¿en qué te fijas primero cuando alguien te atrae? Sin nombres, o toma 3.`,
`tr|{j}, reparte 4 sorbos entre quienes hayan tenido una cita este mes. Si no hay nadie, tómalos tú.`,
`rg3|{j} pone la regla: por 3 rondas, todos responden mirando a los ojos a quien pregunta. Quien mire al piso, toma 2.`]},
{id:'conflicto',nm:'Conflicto',em:'⚡',c:'#ff8c42',ds:'Votaciones incómodas. Sin llorar.',lvl:2,deck:[
`vt|Voten: ¿quién deja en visto con más frialdad? Toma 3.`,
`vt|Voten: ¿quién es más probable que olvide tu cumpleaños? Toma 2.`,
`vs|{j} vs {j2}: debate de 30 segundos. Tema: "el reguetón es cultura". {j} a favor, {j2} en contra. El grupo elige perdedor: toma 3.`,
`vt|Voten: ¿quién pide "un poquito" de tu comida y se come la mitad? Toma 3.`,
`p|{j}, di algo que el grupo hace y te molesta en secreto. Si confiesas, toma 1 por valiente; si no, toma 3.`,
`vt|Voten: ¿quién tarda más en arreglarse? Toma 2.`,
`vs|{j} vs {j2}: brazo extendido sosteniendo el vaso. El que lo baje primero toma 3.`,
`vt|Voten: ¿quién es más terco? Los dos más votados toman 2 cada uno.`,
`p|{j}, sinceridad: ¿quién del grupo vive pegado al celular en las juntas? Esa persona toma 2.`,
`vt|Voten: ¿quién cancela planes a última hora? Toma 3 y promete cambiar (mentira).`,
`vs|{j} vs {j2}: guerra de cumplidos pasivo-agresivos. El grupo corona al más filoso; el otro toma 2.`,
`vt|Voten: ¿quién manda audios de 3 minutos? Toma 3.`,
`rg3|Prohibido defenderse de las votaciones. Quejarse = 1 sorbo extra.`,
`vt|Voten: ¿quién ganaría una discusión sin tener razón? Toma 3 como trofeo.`,
`vt|Voten: ¿quién es el más chismoso justo cuando uno no está? El más votado toma 3 sorbos.`,
`vt|Voten: ¿quién se adueña del parlante y no suelta la música en toda la noche? El campeón toma 2 sorbos.`,
`vt|Voten: ¿quién consigue siempre lo que quiere poniendo cara de pena? El elegido toma 3 sorbos.`,
`vt|Voten: ¿quién hace un drama de proporciones por un problema del porte de una hormiga? Toma 2 sorbos.`,
`vt|Voten: ¿quién le echa la culpa al taco o al despertador cuando en realidad se quedó dormido? Toma 3 sorbos.`,
`vt|Voten: ¿quién se demora media hora eligiendo qué pedir y al final pide lo de siempre? El indeciso toma 2 sorbos.`,
`vt|Voten: ¿quién promete ayudar con la mudanza o el aseo y después desaparece? El fantasma toma 3 sorbos.`,
`vt|Voten: ¿quién se pica más cuando pierde, aunque sea jugando cartas? El picado toma 2 sorbos.`,
`vt|Voten: ¿quién echa los cumplidos más falsos del grupo? El más votado paga con 3 sorbos.`,
`r|{j}, ponle a cada uno un apodo honesto de una sola palabra. A quien no le guste el suyo, toma 2 sorbos.`,
`vs|{j} vs {j2}: a la cuenta de tres, apunten al que creen más desordenado. Si no coinciden, ambos toman 2 sorbos.`,
`rg3|Prohibido decir "no fue mi culpa". Cada vez que salga la frase, quien la dijo toma 1 sorbo.`,
`tr|{j}, nombra al que más veces ha llegado tarde este año y regálale 3 sorbos. Si nadie te apoya, los tomas tú.`,
`p|{j}, ¿qué mensaje del grupo dejaste en visto a propósito y por qué? Confiesa o toma 3 sorbos.`,
`cc|Ronda de excusas para arrancarse de un plan: {j} parte y nadie puede repetir. Al que le crean menos toma 3 sorbos.`,
`tm15|{j}, antes del pitido dile algo bueno y honesto a cada persona del grupo. Si te falta alguien, tomas 3 sorbos.`]},
{id:'muerte',nm:'Muerte súbita',em:'💀',c:'#f43f5e',ds:'Retos relámpago. Fallar cuesta caro.',lvl:2,deck:[
`tm10|{j}, di 3 nombres del grupo en orden alfabético. Falla = 3 sorbos.`,
`tm10|{j}, cuenta del 20 al 1 al revés sin tropezar. Falla = 3 sorbos.`,
`vs|{j} vs {j2}: par o impar con los dedos, a una. Perdedor: 3 sorbos.`,
`tm10|{j}, nombra 4 colores en inglés. Falla = 3.`,
`cc|Ronda relámpago: animales de granja. Quien dude 3 segundos toma 3.`,
`tm10|{j}, deletrea MURCIÉLAGO sin equivocarte. Falla = 3.`,
`vs|{j} vs {j2}: "tres tristes tigres" a máxima velocidad. El grupo decide; perdedor toma 3.`,
`tm10|{j}, di 5 frutas que no sean rojas. Falla = 3.`,
`dd|{j}, dado de la muerte: con 1 o 6 estás a salvo; cualquier otro número, tómalo en sorbos.`,
`tm10|{j}, repite exacto el ritmo de aplausos que invente {j2}. Falla = 3.`,
`vs|{j} vs {j2}: piedra, papel o tijera a UNA ronda (empate se repite). Perdedor toma 3.`,
`tm10|{j}, nombra 3 películas con números en el título. Falla = 3.`,
`tm10|{j}, di tres veces seguidas "el suelo está enladrillado" sin trabarte. Si te enredas, tomas 3 sorbos.`,
`tm12|{j}, nombra 5 series o películas que hayas visto este año antes del pitido, o tomas 3 sorbos.`,
`tm12|{j}, di el abecedario completo salteando todas las vocales, sin pausas. Si te pierdes, tomas 3 sorbos.`,
`tm12|{j}, suelta 4 chilenismos que un gringo jamás entendería. Si dudas o repites, tomas 3 sorbos.`,
`tm15|{j}, cuenta tu día de ayer al revés, desde que te acostaste hasta que despertaste. Falla y tomas 3 sorbos.`,
`tm10|{j}, di el nombre de {j2} al revés, letra por letra. Si te enredas, tomas 3 sorbos.`,
`vs|{j} vs {j2}: el grupo grita una letra. El primero en decir una comida que empiece así gana; el otro toma 3 sorbos.`,
`vs|{j} vs {j2}: tírense palabras por turnos y respondan lo primero que se les venga. Quien dude dos segundos toma 3 sorbos.`,
`vs|{j} vs {j2}: invéntense una palabra con cara de diccionario. El grupo elige la más creíble; el otro toma 3 sorbos.`,
`vs|{j} vs {j2}: canten la misma vocal sostenida. El primero en quedarse sin aire toma 3 sorbos.`,
`vs|{j} vs {j2}: armen una historia absurda agregando una frase cada uno, por turnos. El primero en trabarse toma 3 sorbos.`,
`vs|{j} vs {j2}: cuenten cómo llegaron hoy al carrete sin usar la letra A. El primero que la diga toma 3 sorbos.`,
`dd|{j}, lanza el dado mientras {j2} piensa un número del 1 al 6. Si coinciden, {j2} toma 3 sorbos; si no, tomas tú 3.`,
`dd|{j}, lanza el dado dos veces. Si el segundo número es mayor que el primero te salvas; si no, tomas 3 sorbos.`,
`cc|Cosas que uno lleva a un asado. Ronda relámpago: {j} parte. Quien dude o repita toma 3 sorbos.`,
`cc|Grupos y solistas chilenos. Ronda relámpago: {j} arranca. Quien falle o repita toma 3 sorbos.`]},
{id:'noventas',nm:'90\'s',em:'📼',c:'#22d3ee',ds:'Nostalgia pura para millennials.',lvl:1,deck:[
`r|{j}, tararea un tono de celular clásico de los 2000. Si nadie lo reconoce, tomas 2.`,
`p|{j}, ¿VHS o DVD marcó tu infancia? Los del otro bando toman 1.`,
`yn|Yo nunca he soplado un cartucho de videojuego. Los que sí, toman 1 con nostalgia.`,
`cc|Caricaturas de los 90 y 2000. {j} empieza. Falla = 3.`,
`r|{j}, baila la coreografía de alguna canción noventera 10 segundos o toma 2.`,
`p|{j}, ¿cuál era tu programa de TV favorito de niño? Si alguien más lo veía, toman 1 juntos.`,
`yn|Yo nunca quemé un CD con música descargada. Toma 2, pirata retro.`,
`mm|{j}, actúa: "esperar a que cargue una página con internet por teléfono". Si adivinan, todos toman 1; si no, tomas 2.`,
`r|{j}, di "hola como estas" letra por letra como si escribieras en un teclado T9. Si te aburres, 2 sorbos.`,
`vt|Voten: ¿quién tiene el alma más noventera? Toma 2 con honor.`,
`p|{j}, ¿walkman, discman o mp3: cuál usaste primero? Quienes no usaron ninguno toman 1 por jóvenes.`,
`tm20|{j}, nombra 5 juguetes clásicos antes del pitido o toma 3.`,
`yn|Yo nunca he llorado con una película animada. Quien no tome está mintiendo 😏.`,
`r|{j}, cuenta la peor caída que te pegaste en bici o patines cuando chico. Si el grupo no grita "auch", tomas 2.`,
`r|{j}, describe tu pieza de cuando tenías 10 años sin nombrar ningún aparato con pantalla. Si se te escapa uno, tomas 2.`,
`r|{j}, imita cómo caminabas por el pasillo del colegio arrastrando la mochila con ruedas. Si nadie se ríe, tomas 2.`,
`r|{j}, párate firme y recita el juramento a la bandera como en el acto del lunes. Si no llegas a la mitad, tomas 2.`,
`p|{j}, ¿cómo se llamaba tu profesora jefe de primero básico? Si no te acuerdas del nombre, tomas 2.`,
`p|{j}, ¿qué ibas a hacer al ciber: jugar en red o chatear? Cuenta una anécdota concreta o toma 2.`,
`p|{j}, ¿cuál era el peor castigo en tu casa: sin tele, sin salir o parado en el rincón? Si alguien cuenta uno peor, tomas 2.`,
`p|{j}, adivina cuántos del grupo alcanzaron a usar un teléfono público con monedas. Si le achuntas, repartes 3; si no, tomas 2.`,
`yn|Yo nunca usé un mapa de papel para no perderme en un viaje familiar. Quien sí, toma 2.`,
`yn|Yo nunca perdí una partida porque se le acabaron las pilas al control. Quien sí, toma 2.`,
`yn|Yo nunca copié una tarea entera de una enciclopedia de papel. Quien sí, toma 2.`,
`vt|{j} nomina a dos y el grupo vota: ¿quién se sabe más jingles de comerciales antiguos? El elegido canta uno o toma 3.`,
`mm|{j}, actúa sin hablar: cambiarle el lado al cassette justo en la mejor parte. Si adivinan, todos toman 1; si no, tomas 2.`,
`vs|{j} vs {j2}: quién nombra más juegos de patio, la pinta, el luche y los que sigan, en 20 segundos. El que se queda sin, toma 3.`,
`pc|{j}, di en voz alta tu primer correo electrónico completo, el vergonzoso§Reparte 3 sorbos a quien quieras§Toma 3 sorbos`,
`rg3|Por 3 rondas nadie puede decir "wifi", "app" ni "celular": hay que explicarlo a la antigua. Quien falle toma 1.`]},
{id:'nunca',nm:'Nunca nunca',em:'🙊',c:'#a78bfa',ds:'Quien SÍ lo hizo toma 2. Sin excusas.',lvl:2,deck:[
`yn|Yo nunca me he hecho el dormido para no hablar con alguien.`,
`yn|Yo nunca he olvidado el nombre de alguien mientras lo presentaba.`,
`yn|Yo nunca he respondido "jajaja" sin reírme ni un poco.`,
`yn|Yo nunca he entrado a una reunión online sin pantalones formales.`,
`yn|Yo nunca he fingido una llamada para escapar de una conversación.`,
`yn|Yo nunca he comido algo del piso invocando la regla de los 5 segundos.`,
`yn|Yo nunca he dicho "ya voy en camino" estando en pijama.`,
`yn|Yo nunca he stalkeado al ex de mi ex.`,
`yn|Yo nunca me he reído en un momento totalmente inapropiado.`,
`yn|Yo nunca he cantado en la ducha como si fuera un concierto.`,
`yn|Yo nunca he devuelto un "te quiero" sin sentirlo del todo.`,
`yn|Yo nunca he mentido en este juego. (Quien tome aquí, toma doble 😈).`,
`yn|Yo nunca he llorado por una serie.`,
`yn|Yo nunca he usado la misma excusa dos veces con la misma persona.`,
`yn|Yo nunca he revisado el celular de alguien sin permiso.`,
`yn|Yo nunca he dicho "sí, obvio que voy" a un plan que en el fondo no quería. Quien sí, toma 2 sorbos.`,
`yn|Yo nunca me he echado perfume en vez de ducharme por pura flojera. Los culpables toman 2 sorbos.`,
`yn|Yo nunca me he quedado con hambre por vergüenza de repetirme el plato en la casa de otra persona. Quien sí, 2 sorbos.`,
`yn|Yo nunca he dejado un producto botado en otro pasillo del súper por flojera de ir a devolverlo. Quien sí, 2 sorbos.`,
`yn|Yo nunca he comprado algo que no necesitaba solo porque decía "70% de descuento". Si te pasó, toma 2 sorbos.`,
`yn|Yo nunca he borrado una foto de mis redes porque tuvo menos likes de los que esperaba. Quien sí, 2 sorbos.`,
`yn|Yo nunca he escuchado los audios de un amigo en velocidad rápida para terminar antes. Los apurados toman 2 sorbos.`,
`yn|Yo nunca he apagado la alarma pensando "5 minutos más" y desperté dos horas después. Quien sí, toma 2 sorbos.`,
`yn|Yo nunca he buscado a escondidas una palabra a mitad de la conversación para no quedar como tonto. Quien sí, 2 sorbos.`,
`yn|Yo nunca he dicho "después te transfiero" y se me olvidó por completo. Los morosos toman 2 sorbos.`,
`yn|Yo nunca he comido algo a escondidas en la cocina para no tener que compartirlo. Quien sí, toma 2 sorbos.`,
`yn|Yo nunca me he probado ropa en una tienda sabiendo perfectamente que no la iba a comprar. Quien sí, 2 sorbos.`,
`yn|Yo nunca he guardado un número con un apodo que esa persona jamás debería ver. Quien sí, toma 2 sorbos.`,
`yn|Yo nunca he saludado de vuelta a alguien que en realidad estaba saludando a la persona de atrás. Quien sí, 2 sorbos.`,
`yn|Yo nunca he mandado un mensaje al chat equivocado y lo he borrado a toda velocidad. Quien sí, toma 2 sorbos.`,
`yn|Yo nunca he dejado la ropa acumulada en la silla del dormitorio en vez de guardarla. Los culpables toman 2 sorbos.`]},
{id:'shot',nm:'Shot',em:'🥃',c:'#fb7185',ds:'Todo shot se puede cambiar por 3 sorbos. Nadie está obligado.',lvl:2,deck:[
`sh|{j}, shot o karaoke: canta 20 segundos de la canción que elija el grupo.`,
`sh|{j} y {j2}: shot en espejo. Uno guía los movimientos, el otro imita. O ambos toman 2 y paz.`,
`sh|{j}, shot o responde una verdad incómoda a elección del grupo.`,
`sh|{j}, gira una botella (o tu dedo con ojos cerrados). El señalado: shot o 3 sorbos.`,
`sh|{j}, brinda un shot con la persona que menos conoces del grupo… o cuéntale un secreto leve.`,
`sh|{j}, shot o 10 sentadillas ahora mismo.`,
`sh|El último que llegó hoy: shot de bienvenida tardía o 3 sorbos.`,
`sh|{j}, prepara un "shot misterioso" solo con cosas comestibles y seguras. {j2} lo prueba o toma 3.`,
`sh|{j}, shot o imita a un famoso hasta que alguien adivine.`,
`sh|Shot comunitario: todos los que tengan menos de 20% de batería.`,
`aq|Intermedio obligatorio: vaso de agua antes del próximo shot. En serio.`,
`sh|{j}, shot o deja que el grupo elija tu foto de perfil por 24 horas.`,
`sh|{j}, shot o baila 15 segundos sin música con toda la seriedad del mundo.`,
`sh|{j}, shot o adivina en qué mano escondió {j2} una moneda. Si fallas, 3 sorbos.`,
`sh|{j}, shot o di "el cielo está enladrillado, quién lo desenladrillará" sin trabarte. Si te enredas, 3 sorbos.`,
`sh|{j}, shot o ponte de pie cada vez que alguien tome, hasta la próxima carta. Si se te olvida, 3 sorbos.`,
`sh|{j}, shot o acepta el apodo que te ponga el grupo por lo que queda de noche. Si no respondes a él, 1 sorbo.`,
`sh|{j}, shot o cuenta cuál fue tu última compra inútil y cuánto te costó. Si te achicas, 3 sorbos.`,
`sh|{j}, shot o hazte cargo de la música hasta la próxima carta. Si pones una penca, 3 sorbos.`,
`sh|{j}, shot o comprométete a lavar los vasos al final del carrete. Si te arrepientes ahora, 3 sorbos.`,
`sh|{j}, shot o deja que {j2} elija tu pose para la próxima foto grupal. Si te niegas, 3 sorbos.`,
`sh|{j}, shot o camina como pingüino hasta la cocina y de vuelta. Si te da lata, 3 sorbos.`,
`sh|{j}, shot o léele al grupo tu horóscopo de hoy como si fuera noticia de último minuto. Si no, 3 sorbos.`,
`sh|{j}, shot o entrevista a {j2} como reportero de farándula sobre el evento del año. Si dura menos de 20 segundos, 3 sorbos.`,
`sh|{j}, shot o deja el celular en modo avión por 15 minutos. Si lo revisas antes, 3 sorbos.`,
`sh|{j}, shot o dile a {j2} qué canción le pondrías de fondo cada vez que entra a una pieza. Si nadie se ríe, 3 sorbos.`,
`sh|{j}, shot o cede tu asiento al que esté peor sentado por lo que queda de noche. Si lo recuperas, 3 sorbos.`,
`sh|{j}, shot o habla solo con preguntas hasta la próxima carta. A la primera afirmación, 3 sorbos.`,
`dd|{j}, lanza el dado: si sale par, shot o 3 sorbos; si sale impar, toma esa cantidad de sorbos.`]},
{id:'uni',nm:'Universidad',em:'🎓',c:'#60a5fa',ds:'Para mechones, novatos y sobrevivientes.',lvl:1,deck:[
`p|{j}, ¿tu peor excusa para no entregar un trabajo? Si es buena, todos toman 1; si es mala, tomas 2.`,
`yn|Yo nunca he estudiado TODO la noche anterior al examen. Toma 2, leyenda.`,
`r|{j}, expón 20 segundos sobre un tema que no dominas, con total confianza. Si convences, repartes 3.`,
`cc|Carreras universitarias. Falla = 3.`,
`yn|Yo nunca me he dormido en clases. Toma 2.`,
`vt|Voten: ¿quién es el que siempre pide los apuntes? Toma 3.`,
`p|{j}, en trabajos en grupo: ¿líder, aportador o fantasma? Confiesa. Los fantasmas toman 2.`,
`r|{j}, defiende esta tesis 20 segundos: "las tareas para la casa deberían ser ilegales". Sin risas del público, tomas 2.`,
`yn|Yo nunca he ido a clases solo por la asistencia. Toma 1.`,
`tm15|{j}, nombra 5 ramos o materias que hayas odiado. Rápido o toma 2.`,
`vs|{j} vs {j2}: ¿cuánto es 7 × 8 + 4? El más lento toma 2.`,
`rg3|Todos deben llamarse "colega" entre sí. Olvido = 1 sorbo.`,
`p|{j}, ¿qué le dirías a tu yo de primer año? Todos brindan 1 por eso.`,
`yn|Yo nunca he copiado una respuesta en una prueba mirando de reojo. Quien sí, 2 sorbos.`,
`r|{j}, resume tu tesis, tu práctica o tu último trabajo en una frase que entienda tu abuela. Si lo logras, repartes 2 sorbos; si no, tomas 2.`,
`p|{j}, ¿cuál es el ramo que más terror te da o te dio en la vida? Cuéntalo o toma 2 sorbos.`,
`vt|{j} abre la votación: ¿quién manda el "¿alguien fue a clases hoy?" en el chat del curso? El más votado, 3 sorbos.`,
`tm20|{j}, explica qué hace alguien de tu carrera sin decir cómo se llama. Si no adivinan antes del pitido, 2 sorbos.`,
`dd|{j}, lanza el dado: del 1 al 3 confiesas la peor nota de tu vida; del 4 al 6 tomas 2 sorbos.`,
`vt|{j} dirige la votación: ¿quién entrega los trabajos tres semanas antes? Esa persona reparte 3 sorbos.`,
`tr|{j}, reparte 3 sorbos entre los que todavía deben un trabajo atrasado.`,
`p|{j}, cuenta tu mejor historia de mechoneo, la que viviste o la que le hiciste a un novato. O 2 sorbos.`,
`yn|Yo nunca he fingido que se me cortó el internet para no exponer en una clase online. Quien sí, 2 sorbos.`,
`vs|{j} vs {j2}: cuenten su peor experiencia en un trabajo en grupo. El grupo elige la más trágica; el otro toma 2 sorbos.`,
`p|{j}, ¿cuál es el mejor rincón del campus para dormir una siesta entre clases? Descríbelo o toma 2 sorbos.`,
`r|{j}, pon la cara que se te sale cuando el profe dice "esto entra en la prueba". Si el grupo se ríe, repartes 2 sorbos; si no, tomas 2.`,
`yn|Yo nunca he pensado en serio en cambiarme de carrera. Quien sí, 2 sorbos.`,
`p|{j}, ¿cuál ha sido tu peor bloqueo mental en plena prueba? Cuéntalo o toma 2 sorbos.`,
`rg2|Regla de {j}: cada vez que alguien diga "profe", todos responden "presente". Quien se olvide, 1 sorbo.`]},
{id:'fit',nm:'Fit',em:'💪',c:'#34d399',ds:'Retos físicos. Sudar o tomar.',lvl:1,deck:[
`r|{j}, 10 sentadillas o toma 3. El grupo cuenta en voz alta.`,
`r|Plancha grupal 20 segundos. Quien caiga primero toma 2.`,
`vs|{j} vs {j2}: quién aguanta más en cuclillas contra la pared. Perdedor toma 3.`,
`r|{j}, 15 jumping jacks con sonrisa obligatoria o toma 2.`,
`tm30|Todos en equilibrio sobre un pie hasta el pitido. Quien toque el piso toma 2.`,
`r|{j}, tócate la punta de los pies sin doblar rodillas. ¿Llegas? Repartes 2. ¿No? Tomas 2.`,
`vs|{j} vs {j2}: guerra de pulgares al mejor de 3. Perdedor toma 2.`,
`r|{j}, 5 flexiones estilo libre (con rodillas vale). O toma 3.`,
`r|{j}, camina en cámara lenta exagerada de un extremo al otro. Si {j2} (el jurado) no aprueba, tomas 2.`,
`tm20|{j}, trota en el lugar hasta el pitido con ánimo de final olímpica. Rendirse = 3 sorbos.`,
`r|{j}, sostén tu vaso con el brazo extendido 30 segundos. Si tiembla mucho (decide el grupo), toma 2.`,
`r|Sesión de estiramiento de 20 segundos dirigida por {j}. Quien no participe toma 2.`,
`r|{j}, estira los brazos al techo y quédate en la punta de los pies 10 segundos. Si te tambaleas, tomas 2 sorbos.`,
`r|{j}, haz 8 círculos lentos con cada hombro hacia atrás mientras el grupo cuenta. Si te saltas alguno, tomas 1 sorbo.`,
`r|{j}, siéntate en el suelo con las piernas cruzadas y levántate sin usar las manos. Si no puedes, tomas 2 sorbos.`,
`r|{j}, junta las palmas detrás de la espalda, codos hacia atrás, y aguanta 10 segundos. Si no llegas, tomas 2 sorbos.`,
`r|{j}, haz 6 sentadillas bien lentas, tres segundos bajando y tres subiendo. Si aceleras, tomas 2 sorbos.`,
`r|{j}, camina de puntillas hasta {j2} y vuelve sin apoyar los talones. Si los apoyas, tomas 2 sorbos.`,
`tm20|{j}, respira lento hasta el pitido: cuatro segundos inhalando, cuatro exhalando. Si hablas o te ríes, tomas 2 sorbos.`,
`tm15|{j}, dobla el torso a un lado con el brazo estirado sobre la cabeza y cambia de lado a la mitad, o tomas 2 sorbos.`,
`tm15|Todos giren el cuello lento, de un hombro al otro, hasta el pitido. Quien lo haga a la rápida toma 1 sorbo.`,
`vs|{j} vs {j2}: sentados, quién aguanta más con las piernas estiradas al frente. El primero en bajarlas toma 2 sorbos.`,
`vs|{j} vs {j2}: caminen con un cojín en la cabeza hasta la puerta y vuelvan. El primero en botarlo toma 2 sorbos.`,
`dd|{j}, lanza el dado: esa cantidad de veces sube una rodilla al pecho, sin saltar. Si no llegas, tomas 2 sorbos.`,
`rg2|Durante 2 rondas todos se sientan con la espalda derecha y los pies en el suelo. Quien se encorve toma 1 sorbo.`,
`yn|Yo nunca he pagado un gimnasio al que fui menos de tres veces. Si te pasó, toma 2 sorbos.`,
`p|{j}, ¿cuándo fue la última vez que hiciste deporte de verdad? Si no te acuerdas, tomas 2 sorbos.`,
`tr|{j}, reparte 3 sorbos entre los que no han estirado ni un músculo en toda la noche.`]},
{id:'versus',nm:'Versus',em:'⚔️',c:'#f59e0b',ds:'Duelos 1 vs 1. Solo puede quedar uno.',lvl:2,deck:[
`vs|{j} vs {j2}: quién nombra más capitales por turnos en 20 segundos. Perdedor toma 3.`,
`vs|{j} vs {j2}: duelo de talentos ocultos de 15 segundos. El grupo vota; perdedor toma 3.`,
`vs|{j} vs {j2}: cada uno tararea el coro de una canción sin decir el nombre. El primero que adivine la del otro gana; el que no adivina toma 3 sorbos.`,
`vs|{j} vs {j2}: sonrisa falsa sostenida mientras el grupo intenta hacerlos reír de verdad. Perdedor toma 2.`,
`vs|{j} vs {j2}: deletreen OTORRINOLARINGÓLOGO. El más rápido y correcto gana; perdedor toma 3.`,
`vs|{j} vs {j2}: batalla de baile de 15 segundos. Perdedor toma 3, ganador reparte 2.`,
`vs|{j} vs {j2}: el grupo piensa un número del 1 al 10 en secreto. Quien diga el más lejano toma 2.`,
`vs|{j} vs {j2}: piedra, papel o tijera a 5 rondas relámpago. Perdedor toma 3.`,
`vs|{j} vs {j2}: imiten un animal que elija el grupo. El menos convincente toma 2.`,
`vs|{j} vs {j2}: digan el abecedario alternando letras y mirándose fijo. El que se equivoque toma 3.`,
`vs|{j} vs {j2}: quién dice más palabras que empiecen con TR en 15 segundos. Perdedor toma 2.`,
`vs|{j} vs {j2}: duelo de datos inútiles, uno cada uno hasta que alguien se quede sin. Perdedor toma 3.`,
`vs|{j} vs {j2}: quién hace reír primero al otro solo con gestos. Perdedor toma 2.`,
`vs|{j} vs {j2}: a la cuenta de tres digan un color en voz alta. Si coinciden se salvan; si no, ambos toman 2 sorbos.`,
`vs|{j} vs {j2}: descríbanse el uno al otro en tres palabras, al mismo tiempo. El grupo elige al más certero; el otro toma 2 sorbos.`,
`vs|{j} vs {j2}: palabras encadenadas, cada una parte con la última sílaba de la anterior. El primero en trabarse toma 3 sorbos.`,
`vs|{j} vs {j2}: cada uno cuenta en 10 segundos una mentira creíble sobre sí mismo. El grupo cacha cuál es más falsa; esa persona toma 2 sorbos.`,
`vs|{j} vs {j2}: dibujen en el aire con el dedo lo que pida el grupo, sin hablar. El dibujo menos claro toma 2 sorbos.`,
`vs|{j} vs {j2}: cuenten del 1 al 20 diciendo "carreteo" en los múltiplos de 3. El primero que se equivoque toma 3 sorbos.`,
`vs|{j} vs {j2}: el grupo dicta una palabra rara. El primero en usarla en una frase con sentido gana; el otro toma 2 sorbos.`,
`vs|{j} vs {j2}: narren 10 segundos lo que pasa en la mesa como relatores de fútbol. El menos épico toma 2 sorbos.`,
`vs|{j} vs {j2}: cada uno propone un panorama para el sábado. El grupo elige el más penca y esa persona toma 2 sorbos.`,
`vs|{j} vs {j2}: {j} da una pista tipo "veo veo" de algo del lugar. Si {j2} no adivina en 10 segundos toma 3 sorbos; si acierta, {j} toma 2.`,
`vs|{j} vs {j2}: el grupo dice una emoción y ambos la actúan solo con la cara, a la vez. El menos expresivo toma 2 sorbos.`,
`vs|{j} vs {j2}: {j} nombra cuatro objetos al azar y {j2} los repite en orden. Si falla toma 3 sorbos; si acierta, {j} toma 2.`,
`vs|{j} vs {j2}: cada uno vende en 10 segundos el objeto más penca que tenga a mano. El peor vendedor toma 2 sorbos.`,
`vs|{j} vs {j2}: pónganle un apodo nuevo al otro en cinco segundos. El grupo elige el mejor; el perdedor toma 2 sorbos.`,
`vs|{j} vs {j2}: quién dice primero tres cosas que los dos tengan puestas ahora mismo. El más lento toma 2 sorbos.`,
`vs|{j} vs {j2}: quién recuerda más nombres del grupo con apellido incluido. El que se quede corto toma 2 sorbos.`]},
{id:'invierno',nm:'Invierno',em:'❄️',c:'#7dd3fc',ds:'Team frazada, este es su momento.',season:true,lvl:1,deck:[
`p|{j}, ¿tu plan perfecto de invierno: película, comida y compañía? Descríbelo o toma 2.`,
`r|{j}, abraza a {j2} tipo "pingüino en tormenta" por 5 segundos. Ambos toman 1 de calorcito.`,
`yn|Yo nunca me he negado a salir por frío. Toma 2, team frazada.`,
`cc|Cosas calientes: bebidas, comidas o lugares. Falla = 3.`,
`r|{j}, imita a alguien entrando al mar helado. Si el grupo tirita contigo, repartes 2.`,
`vt|Voten: ¿quién es más friolento? Toma 2 bien abrigado.`,
`p|{j}, ¿chocolate caliente, café o té? Tu bando toma 1 unido.`,
`tm15|{j}, nombra 4 deportes de invierno o toma 2.`,
`r|El último en ponerse algo extra "de abrigo" (real o improvisado) toma 2.`,
`yn|Yo nunca he dormido con calcetines. Los polares toman 1.`,
`mm|{j}, actúa: muñeco de nieve derritiéndose. Adivinan = todos toman 1; no = tomas 2.`,
`p|{j}, cuenta tu mejor recuerdo de unas vacaciones de invierno o toma 2.`,
`p|{j}, ¿cuál es tu mejor truco para salir de la cama con frío? Si a alguien le sirve, reparte 2; si no, toma 2.`,
`p|{j}, ¿sopaipillas con pebre o con chancaca? Los que elijan la otra opción toman 1.`,
`yn|Yo nunca me he quemado con el guatero. Los torpes del calorcito toman 2.`,
`yn|Yo nunca he usado el mismo polerón tres días seguidos en invierno. Toma 2, sin vergüenza.`,
`r|{j}, consigue que alguien del grupo te preste algo que te abrigue por 2 rondas. Si nadie te presta nada, toma 2; si te prestan, repartes 2.`,
`r|{j}, dramatiza tu reacción exacta cuando se corta la calefacción a medianoche. Si el grupo se ríe, reparte 2; si no, toma 2.`,
`p|{j}, ¿la sopa es un plato de verdad o puro trámite antes de la comida? Defiende tu postura o toma 2.`,
`vt|Voten: ¿quién cancela un carrete apenas cae la primera gota de lluvia? Toma 2.`,
`tr|{j}, reparte 3 sorbos de a uno y di en voz alta por qué le toca a cada uno. Si te quedas sin razón, te lo tomas tú.`,
`rg2|Lenguaje corporal delator: quien tirite, se sople las manos o se abrace solo, toma 1.`,
`tm20|{j}, cuéntanos tu domingo de lluvia ideal sin decir 'casa', 'cama' ni 'nada'. Si se te escapa una antes del pitido, toma 2.`,
`mm|{j}, actúa: alguien saliendo de una ducha caliente directo a un pasillo helado. Si adivinan, todos toman 1; si no, tomas 2.`,
`cc|Prendas para el frío: gorro, bufanda, calcetines gruesos. {j} empieza, sigan en ronda. El que falla o repite toma 3.`,
`p|{j}, ¿cuántas marraquetas con mantequilla te comes en una once de invierno? Di el número real o toma 2.`,
`p|{j}, ¿qué serie o película repites cada invierno bajo la frazada? Si alguien más la ha visto, ambos toman 1.`,
`pc|{j}, di 'qué frío' con cinco tonos distintos seguidos: rabia, pena, susto, coqueteo y sueño§Reparte 3 sorbos§Toma 3 sorbos`]},
{id:'navidad',nm:'Navidad',em:'🎄',c:'#ef4444',ds:'Ho ho ho con sorbos.',season:true,lvl:1,deck:[
`p|{j}, ¿el regalo más raro que has recibido? Cuéntalo o toma 2.`,
`r|{j}, canta 10 segundos de un villancico con estilo de rockstar o toma 2.`,
`yn|Yo nunca he reciclado un regalo. Toma 2, gestor eficiente.`,
`vt|Voten: ¿quién compra los regalos el 24 a última hora? Toma 3.`,
`cc|Comidas típicas de fin de año. Falla = 3.`,
`r|{j}, da un discurso navideño de 15 segundos que incluya la palabra "renos". Todos toman 1 al final.`,
`mm|{j}, actúa: Papá Noel atascado en la chimenea. Adivinan = repartes 2; no = tomas 2.`,
`p|{j}, ¿cena ideal: familiar tranquila o fiesta total? Tu bando toma 1.`,
`yn|Yo nunca he llorado con una película navideña. Toma 1, corazón de pan de pascua.`,
`r|Todos digan "¡salud y feliz navidad!" al unísono. Quien se adelante o atrase toma 1.`,
`tr|{j}, haz de Viejito Pascuero: reparte 4 sorbos entre quienes se "portaron mal" este año.`,
`p|{j}, un propósito de año nuevo que NO cumpliste. Confiesa o toma 3.`,
`p|{j}, ¿cola de mono o ponche? Los que prefieran la otra bebida toman 1.`,
`p|{j}, ¿en tu casa la cena del 24 es a las 21:00 o cuando esté lista, aunque den las 23:30? Los de horario elástico toman 2.`,
`yn|Yo nunca he comido pan de pascua solo porque estaba ahí, sin que me gustara tanto. Toma 2, generoso.`,
`yn|Yo nunca he abierto un regalo antes de la hora permitida, a escondidas. Los tramposos de Nochebuena toman 2.`,
`r|{j}, mira a alguien del grupo y dile con cara seria qué le va a traer el Viejito Pascuero. Si lo hace reír, reparte 2; si no, toma 2.`,
`r|{j}, hazte pasar por el amigo secreto de {j2} y dale una pista del regalo sin decir qué es. Si {j2} adivina, ambos toman 1; si no, tomas 2.`,
`vt|Voten: ¿quién se pone más sentimental brindando en la cena de Nochebuena? Toma 2.`,
`dd|{j}, tira el dado: esa cantidad de personas tiene que decir qué le pidió al Viejito Pascuero de chico. El que no se acuerde toma 2.`,
`tr|{j}, reparte 3 sorbos entre los que ya tengan comprados sus regalos de este año. Si no hay ninguno, te los tomas tú.`,
`rg2|Cada vez que alguien tome, tiene que nombrar algo que va en el arbolito, sin repetir lo ya dicho. Quien se quede pegado toma 1 extra.`,
`tm20|{j}, envuelve como regalo cualquier cosa que tengas a mano antes del pitido. Si queda presentable, reparte 2; si queda penca, toma 2.`,
`mm|{j}, actúa: alguien fingiendo sorpresa por un regalo que en realidad no le gustó nada. Si adivinan, todos toman 1; si no, tomas 2.`,
`cc|Regalos clásicos de amigo secreto. {j} arranca, sigan en ronda. El que repite o falla toma 3.`,
`p|{j}, ¿ropa interior amarilla para la suerte de año nuevo: mito o religión para ti? Responde o toma 2.`,
`p|{j}, si solo pudieras pedir un deseo con las doce uvas de año nuevo, ¿cuál sería? Dilo en voz alta o toma 2.`,
`pc|{j} y {j2}, de espaldas y a la cuenta de tres, digan el mismo regalo clásico de amigo secreto§Reparten 3 sorbos entre el grupo§Ambos toman 2 sorbos`]},
{id:'premio',nm:'Premio o castigo',em:'🎁',c:'#22c55e',ds:'Lo logras y ganas. Fallas y pagas.',lvl:2,deck:[
`pc|{j}, lanza una tapa de bebida y haz que caiga dentro de un vaso vacío a un metro. Un solo intento§Reparte 3 sorbos, bacán§Toma 2 sorbos`,
`pc|{j}, apila 5 objetos de la mesa en una torre que quede sola 3 segundos. Tienes 15 segundos para armarla§Elige quién toma 2 sorbos§Toma 2 sorbos`,
`pc|{j}, haz malabares con dos objetos livianos de la mesa durante 10 segundos sin que se te caigan§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, quítate un zapato y vuelve a ponértelo sin usar las manos, en menos de 20 segundos§Reparte 3 sorbos§Toma 3 sorbos`,
`pc|{j}, aguanta 15 segundos respondiendo lo que te pregunte {j2} sin decir ninguna palabra con la letra A§Ambos reparten 2 sorbos§Toma 3 sorbos`,
`pc|{j}, escucha las 5 palabras al azar que dirá {j2} y repítelas todas en el mismo orden§Reparte 3 sorbos§Toma 3 sorbos`,
`pc|{j}, mira a {j2} 10 segundos, cierra los ojos y nombra 4 prendas o accesorios que trae puestos§Reparte 2 sorbos§Toma 2 sorbos`,
`pc|{j}, mira la mesa 5 segundos y cierra los ojos. {j2} esconde un objeto: adivina cuál falta§Elige quién toma 3 sorbos§Toma 3 sorbos`,
`pc|{j}, cierra los ojos y nombra en orden a las 5 personas más cercanas a ti, partiendo por tu derecha§Reparte 2 sorbos§Toma 2 sorbos`,
`pc|{j}, di el nombre completo de {j2}, con sus dos apellidos y sin ayuda de nadie§Manda a {j2} a tomar 2 sorbos§Toma 2 sorbos`,
`pc|{j}, di 5 palabras que rimen con carrete. Inventadas no valen y el grupo es el juez§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, toca 4 cosas de distinto color que tengas a tu alcance antes de que el grupo cuente hasta 5§Elige quién toma 2 sorbos§Toma 2 sorbos`,
`pc|{j}, di el abecedario completo saltándote todas las vocales, de corrido y sin pensarlo§Te libras de la próxima carta§Toma 3 sorbos`,
`pc|{j}, adivina quién del grupo tiene menos batería en el celular. Se revisa al tiro§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, invéntale un apodo nuevo a 3 personas del grupo al tiro. Si a las 3 les gusta, ganas§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, adivina qué tiene {j2} de fondo de pantalla en el celular. {j2} lo muestra para confirmar§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, nombra el mes de cumpleaños de 3 personas del grupo. Puedes fallar en una§Reparte 3 sorbos§Toma 3 sorbos`,
`pc|{j}, adivina la película o serie favorita de {j2} en un solo intento§Ambos reparten 2 sorbos§Toma 2 sorbos`,
`pc|{j}, nombra 3 cosas que {j2} jamás haría. Si {j2} valida al menos 2, ganas§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, di algo que {j2} SIEMPRE hace en las juntas y que no pueda desmentir§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, vende el objeto que tengas más cerca como comercial de teletienda: 15 segundos sin parar de hablar§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, narra los próximos 15 segundos del carrete como comentarista deportivo en la final§Elige la música de la próxima canción§Toma 2 sorbos`,
`pc|{j}, hazle una entrevista de trabajo bien seria a {j2} por 15 segundos, sin reírte ni una vez§Ambos reparten 2 sorbos§Toma 3 sorbos`,
`pc|{j}, di "ya voy saliendo" tres veces: enojado, enamorado y aterrado. El grupo tiene que cachar cuál es cuál§Inventa una regla que dure 2 rondas§Toma 3 sorbos`,
`pc|{j}, ponte a llorar de mentira en 5 segundos, bien convincente. El grupo decide si te cree§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, escribe tu nombre completo en el aire con un pie, sin que el pie toque el suelo§Reparte 3 sorbos§Toma 2 sorbos`,
`pc|{j}, siéntate con los dos pies en el aire y aguanta 20 segundos sin apoyarlos ni una vez§Te libras de la próxima carta§Toma 3 sorbos`,
`pc|{j} y {j2}: sostengan el mismo vaso lleno entre los dos, cada uno con un solo dedo, 15 segundos§Ambos reparten 2 sorbos§Ambos toman 2 sorbos`,
`pc|{j}, sostén un cubito de hielo en la mano 20 segundos, sin guante ni servilleta y sin soltarlo§Reparte 4 sorbos§Toma 3 sorbos`,
`pc|{j}, equilibra una moneda en el dorso de tu mano mientras cuentas en voz alta hasta 20§Reparte 2 sorbos§Toma 2 sorbos`]},
{id:'vor',nm:'Verdad o reto',em:'🎲',c:'#0ea5e9',ds:'Eliges tú antes de ver la carta. No hay vuelta atrás.',pick:true,lvl:2,deck:[
`[1]p|{j}, ¿cuál es la comida que jamás probarías, ni por plata? Responde o toma 2.`,
`[1]p|{j}, ¿qué canción te sabes entera y te da vergüenza admitir? Cántala o toma 2.`,
`[2]p|{j}, ¿cuál es la mentira más grande que has dicho para salir de un compromiso? O toma 3.`,
`[2]p|{j}, ¿a quién de acá le pedirías plata prestada sin dudar? Di por qué o toma 2.`,
`[3]p|{j}, ¿cuál es el mensaje que más te arrepientes de haber mandado? Cuéntalo o toma 4.`,
`[3]p|{j}, ¿alguna vez te gustó alguien que no debías? Un sí o un no basta, o toma 3.`,
`[1]r|{j}, habla como locutor de radio hasta tu próximo turno o toma 2.`,
`[1]r|{j}, hazle un cumplido sincero a cada persona del grupo o toma 3.`,
`[2]r|{j}, deja que {j2} elija tu foto de perfil por una hora, o toma 3.`,
`[2]r|{j}, llama a alguien de tu familia y dile que lo quieres, sin explicar por qué. O toma 4.`,
`[3]r|{j}, muéstrale al grupo la última foto que mandaste por WhatsApp, o toma 4.`,
`[3]r|{j}, dile a {j2} qué es lo primero que pensaste cuando lo conociste. Sin filtro o toma 3.`]}
];

/* ---------- juegos especiales ---------- */
const SPECIALS=[
{id:'rey',nm:'Cuarto rey',em:'👑',c:'#eab308',ds:'La baraja clásica, versión digital.'},
{id:'impostor',nm:'Impostor',em:'🕵️',c:'#94a3b8',ds:'Uno miente. Encuéntrenlo.',min:3},
{id:'ruleta',nm:'Ruleta',em:'🎡',c:'#e879f9',ds:'Gira y que decida el destino.'},
{id:'bomba',nm:'La bomba',em:'💣',c:'#f97316',ds:'Pasa el celular antes de que explote.',min:3}
];

/* ---------- cuarto rey ---------- */
const KING_RULES={
'2':`Tú das: elige quién toma 2.`,
'3':`Para ti: tomas 3.`,
'4':`Al suelo: el último en tocar el piso toma 2.`,
'5':`Chicos: los hombres toman 2. Si no hay, todos toman 1.`,
'6':`Chicas: las mujeres toman 2. Si no hay, todos toman 1.`,
'7':`Al cielo: el último en levantar la mano toma 2.`,
'8':`Tu pareja: elige a alguien; cuando tú tomes, esa persona toma contigo hasta el próximo 8.`,
'9':`Rima: di una palabra; en ronda, cada uno dice una que rime. Quien falle toma 3.`,
'10':`Categorías: elige un tema; en ronda, cada uno dice un ejemplo. Quien falle toma 3.`,
'A':`¡Cascada! Todos empiezan a tomar a la vez; nadie puede parar hasta que pare quien tiene a su derecha.`,
'J':`Regla del rey: inventa una regla para lo que queda de juego. Romperla cuesta 2 sorbos.`,
'Q':`Reina preguntona: hazle una pregunta a alguien; esa persona pregunta a otra, y así. Quien responda o dude, toma 2.`,
'K':`¡Rey! Sirve un poco de tu bebida al Vaso del Rey.`
};
const KING_LAST=`👑 ¡CUARTO REY! Te toca el Vaso del Rey. Tómalo… o cámbialo por 5 sorbos y una reverencia.`;

/* ---------- el impostor ---------- */
const IMP_WORDS={
'Comida':['pizza','sushi','empanada','tacos','ramen','asado'],
'Lugares':['playa','aeropuerto','gimnasio','cine','hospital','biblioteca'],
'Animales':['pingüino','tiburón','perezoso','camello','búho','pulpo'],
'Fiesta':['karaoke','piñata','brindis','DJ','confeti','previa'],
'Objetos':['paraguas','linterna','mochila','espejo','almohada','control remoto'],
'Profesiones':['dentista','bombero','chef','astronauta','profesor','taxista'],
'Pantalla':['terror','comedia romántica','documental','anime','telenovela','superhéroes'],
'Deportes':['fútbol','natación','ajedrez','boxeo','tenis','escalada'],
'Transporte':['auto','bicicleta','bus','tren','avión','barco'],
'Clima':['sol','lluvia','nieve','viento','niebla','granizo'],
'Ropa':['polera','chaqueta','jeans','vestido','bufanda','pijama'],
'Emociones':['alegría','tristeza','rabia','miedo','sorpresa','vergüenza']
};

/* ---------- verdad o reto ----------
   Dos mazos separados, cada uno con sus niveles de intensidad.
-------------------------------------*/
const TRUTH_DARE={
truths:[
`[1]p|{j}, ¿cuál es la manía que tienes y que nadie te ha pillado haciendo? Cuéntala o toma 2 sorbos.`,
`[1]p|{j}, ¿qué serie o película has visto más de cinco veces sin cansarte? Responde o toma 2 sorbos.`,
`[1]p|{j}, ¿qué objeto viejo e inútil no botarías ni loco/a? Cuéntanos por qué o toma 2 sorbos.`,
`[1]p|{j}, ¿cuál es la app que más abres al día, aunque no quieras admitirlo? Responde o toma 2 sorbos.`,
`[1]p|{j}, ¿qué mezcla rara de comida te encanta y todos encuentran penca? Cuéntala o toma 2 sorbos.`,
`[1]p|{j}, ¿qué cábala haces para la suerte aunque sepas que es absurda? Explícala o toma 2 sorbos.`,
`[1]p|{j}, ¿cuánto fue tu primer sueldo y en qué te lo gastaste entero? Responde o toma 2 sorbos.`,
`[1]p|{j}, ¿qué muletilla repites sin darte cuenta? Que el grupo confirme o toma 2 sorbos.`,
`[1]p|{j}, ¿a qué le tienes miedo sin ninguna razón lógica? Confiésalo o toma 2 sorbos.`,
`[1]p|Grupal: ¿cuál es la anécdota más antigua que todos recuerdan juntos? Cuéntenla entre todos o todos toman 1 sorbo.`,
`[2]p|{j}, ¿cuál fue tu peor corte de pelo o look que igual subiste a redes? Descríbelo o toma 2 sorbos.`,
`[2]p|{j}, ¿qué hiciste en el colegio que fue tan vergonzoso que nunca se lo contaste a nadie? Cuéntalo o toma 3 sorbos.`,
`[2]p|{j}, ¿qué compraste, usaste una sola vez y nunca más? Responde o toma 2 sorbos.`,
`[2]p|{j}, ¿qué nota o resultado le escondiste a tus papás en su momento? Confiesa o toma 2 sorbos.`,
`[2]p|{j}, ¿qué historia borraste de tus redes a los cinco minutos de subirla? Cuéntala o toma 3 sorbos.`,
`[2]p|{j}, ¿qué comida odias pero te comes igual cuando te invitan a una casa? Responde o toma 2 sorbos.`,
`[2]p|{j}, de los presentes, ¿quién cambia más de opinión según con quién esté hablando? Dilo o toma 2 sorbos.`,
`[2]p|{j}, cuenta una vez que dijiste "obvio, sí" sin tener idea de qué estaban hablando. Cuéntala o toma 2 sorbos.`,
`[2]p|{j}, ¿cuál es la razón real, no la oficial, por la que dejaste tu última pega o carrera? Responde o toma 3 sorbos.`,
`[2]p|{j}, de los presentes, ¿a quién le copiarías el estilo para vestirte mañana? Dilo o toma 2 sorbos.`,
`[3]p|{j}, confiesa algo que hiciste por puros celos y que igual harías de nuevo. Cuéntalo o toma 3 sorbos.`,
`[3]p|{j}, ¿cuánto te demoraste en superar a la persona que más te costó olvidar? Sin nombres, o toma 3 sorbos.`,
`[3]p|{j}, ¿alguna vez cortaste una relación por mensaje en vez de dar la cara? Cuenta qué pasó o toma 3 sorbos.`,
`[3]p|{j}, ¿qué es lo más intenso que hiciste para llamar la atención de alguien que te gustaba? Responde o toma 3 sorbos.`,
`[3]p|{j}, ¿cuál fue la señal obvia que ignoraste entera y hoy te da risa? Cuéntala o toma 3 sorbos.`,
`[3]p|{j}, ¿alguna vez seguiste hablando con alguien solo para no sentirte solo/a? Responde o toma 3 sorbos.`,
`[3]p|{j}, ¿qué cosa de una expareja extrañas y jamás admitirías en voz alta? Admítelo ahora o toma 3 sorbos.`,
`[3]p|{j}, si alguien de tu pasado te escribiera hoy, ¿le contestarías? Un sí o un no basta, o toma 3 sorbos.`,
`[3]p|{j}, ¿qué cumplido te hicieron que todavía recuerdas palabra por palabra? Repítelo o toma 3 sorbos.`,
`[3]p|{j}, ¿qué le perdonaste a alguien después de jurar que jamás se lo perdonarías? Cuéntalo o toma 3 sorbos.`
],
dares:[
`[1]r|{j}, cántale al grupo en modo ópera lo que hiciste hoy, 10 segundos de drama, o toma 3 sorbos.`,
`[1]r|{j}, pon tu cara más seria de foto de LinkedIn y aguanta 10 segundos sin reírte, o toma 3 sorbos.`,
`[1]r|{j}, bautiza a {j2} con un apodo nuevo y explica por qué le queda perfecto, o toma 3 sorbos.`,
`[1]r|{j}, narra como comentarista deportivo todo lo que pase en la sala por 15 segundos, o toma 3 sorbos.`,
`[1]r|{j}, inventa un paso de baile y enséñaselo al grupo hasta que alguien lo haga igual, o toma 3 sorbos.`,
`[1]r|{j}, choca los puños con {j2} y grítale una frase motivacional inventada en el momento, o toma 3 sorbos.`,
`[1]r|{j}, agradécele a {j2} algo mínimo como si te hubiera salvado la vida, o toma 3 sorbos.`,
`[1]r|{j}, agarra el primer objeto que tengas cerca y preséntalo al grupo como tu mascota nueva, o toma 3 sorbos.`,
`[1]r|{j}, ponle a este carrete un nombre de teleserie y anúncialo con voz de tráiler, o toma 3 sorbos.`,
`[1]r|Grupal: en la cuenta de 3, todos posan para la foto y se congelan 5 segundos. El primero que se mueva toma 3 sorbos.`,
`[2]r|{j}, mándale un mensaje de voz cantando un saludo al tercer chat de tu lista, o toma 3 sorbos.`,
`[2]r|{j}, muéstrale al grupo la canción que más escuchaste este mes en tu celular, o toma 3 sorbos.`,
`[2]r|{j}, llama a alguien de tus contactos, dile una adivinanza corta y cuelga apenas conteste, o toma 3 sorbos.`,
`[2]r|{j}, dirige una foto grupal como fotógrafo insoportable hasta que todos queden posando igual, o toma 3 sorbos.`,
`[2]r|{j}, escribe sin enviar un mensaje a tu jefe o profe avisando que tienes una emergencia de carrete, y muéstralo, o toma 3 sorbos.`,
`[2]r|{j}, escríbele "me acordé de ti" a alguien que no ves hace más de un año, o toma 3 sorbos.`,
`[2]r|{j}, sube una historia ahora mismo que diga "carreteando con los mejores", o toma 3 sorbos.`,
`[2]r|{j}, actúa de meteorólogo/a anunciando la previsión del carrete de esta noche por 15 segundos, o toma 3 sorbos.`,
`[2]r|{j}, léele al grupo el título del último video que viste, sin dar ningún contexto, o toma 3 sorbos.`,
`[2]r|{j}, hazle una pataleta de guagua al grupo porque se acabó el hielo, 10 segundos, o toma 3 sorbos.`,
`[3]r|{j}, dile a {j2} cuál sería su red flag si fueran pareja, con humor y cariño, o toma 3 sorbos.`,
`[3]r|{j}, hazle una declaración de amor dramática a tu vaso, como si fuera tu crush, o toma 3 sorbos.`,
`[3]r|{j}, invéntale a {j2} una mini canción de amor de 10 segundos, ahora mismo, o toma 3 sorbos.`,
`[3]r|{j}, muéstrale al grupo cómo le hablarías a alguien que te gusta, usando a {j2} de conejillo de indias, o toma 3 sorbos.`,
`[3]r|{j}, inventa el nombre de usuario que usarías en una app de citas y defiéndelo 10 segundos, o toma 3 sorbos.`,
`[3]r|{j}, si tuvieras que elegir una cita a ciegas entre los presentes, di solo su inicial, o toma 3 sorbos.`,
`[3]r|{j}, pon tu mejor cara de enamorado/a mirando a {j2} durante 5 segundos, sin hablar, o toma 3 sorbos.`,
`[3]r|{j}, hazle a {j2} una propuesta de matrimonio dramática, de rodillas y con anillo imaginario, o toma 3 sorbos.`,
`[3]r|{j}, hazle un cumplido a {j2} en el idioma que elija el grupo, aunque te lo inventes entero, o toma 3 sorbos.`,
`[3]r|{j}, hazle a {j2} esa pregunta que nunca te has atrevido a hacerle. Ahora o nunca, o toma 3 sorbos.`
]
};

/* ---------- la bomba ----------
   Categorías para ir diciendo ejemplos por turnos contra el reloj.
--------------------------------*/
const BOMB_CATS=[
`Verduras`,
`Útiles escolares`,
`Colores`,
`Instrumentos musicales`,
`Razas de perros`,
`Ciudades de Chile`,
`Superhéroes`,
`Cosas que se llevan a la playa`,
`Insectos`,
`Cosas que hay en un living`,
`Marcas de zapatillas`,
`Personajes de dibujos animados`,
`Cosas que se usan en invierno`,
`Países de Europa`,
`Cosas redondas`,
`Herramientas`,
`Palabras que solo dicen los chilenos`,
`Partes del cuerpo`,
`Cosas que dan miedo`,
`Series para ver en streaming`,
`Cosas que hay en un baño`,
`Marcas de bebidas`,
`Animales marinos`,
`Cosas que hacen ruido fuerte`,
`Profesiones de la salud`,
`Cosas que se compran en una farmacia`,
`Cantantes o bandas chilenas`,
`Productos de maquillaje`,
`Tipos de pan`,
`Postres chilenos`,
`Cosas de color amarillo`,
`Ejercicios de gimnasio`,
`Juegos de mesa`,
`Cosas que hay en un supermercado`,
`Marcas de celulares`,
`Cosas que se hacen en la previa`,
`Villanos de películas`,
`Cosas que hay en un estadio de fútbol`,
`Cosas que se comen con las manos`,
`Nombres de hombre comunes en Chile`,
`Nombres de mujer comunes en Chile`,
`Cosas que hay en una oficina`,
`Cosas que se usan para dormir`,
`Tipos de baile`,
`Cosas que hay en un jardín`,
`Cosas que se hacen para relajarse`,
`Objetos que tienen ruedas`,
`Cosas que se usan para cocinar un asado`,
`Comidas típicas chilenas`,
`Cosas típicas de un matrimonio`,
`Aves`,
`Cosas que uno hace apenas se despierta`,
`Marcas de ropa`,
`Sabores de helado`,
`Trabajos que requieren uniforme`,
`Cosas que se hacen los domingos en Chile`,
`Cosas que hay en una fiesta de cumpleaños`,
`Deportes que se juegan con pelota`,
`Frases que dice una mamá chilena`,
`Cosas que se llevan de camping`
];

/* ---------- ruleta ---------- */
const WHEEL_DARES=[
`toma 2 sorbos`,
`reparte 3 sorbos`,
`cuenta un chiste o toma 2`,
`elige quién toma 2`,
`todos toman 1 menos tú`,
`imita a alguien del grupo`,
`di un cumplido a cada persona`,
`toma 1 y gira de nuevo`,
`inventa una regla por 2 rondas`,
`te salvaste: nada esta vez`,
`cuéntale al grupo tu peor mala suerte de carrete o toma 3`,
`todos los que tengan el celular en la mano toman 2`,
`cambia de puesto con quien esté más lejos y toma 1`,
`el grupo vota quién toma 2 en tu lugar`,
`gira de nuevo y lo que salga vale doble`,
`te saltas tu próximo turno, pero antes toma 1`,
`di el nombre completo de cada persona del grupo o toma 2`,
`el último en levantar la mano toma 3`,
`toma 2 por la persona más callada del grupo`,
`aguanta 20 segundos sin reírte mientras el grupo lo intenta, o toma 2`
];

/* El mazo de Verdad o reto es la suma de sus dos listas: así los conteos y
   los tests lo ven como un modo más, pero el juego las reparte por separado. */
MODES.find(m=>m.id==='vor').deck=TRUTH_DARE.truths.concat(TRUTH_DARE.dares);

/* ---------- export para los tests (en el navegador esto se ignora) ---------- */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TYPES, MODES, SPECIALS, KING_RULES, KING_LAST,
                     IMP_WORDS, WHEEL_DARES, TRUTH_DARE, BOMB_CATS };
}
