/* =========================================================
   CARRETEO · cards.js
   TODO el contenido del juego vive aquí. Ninguna lógica.
   Para agregar una carta basta con sumar un string al `deck`
   del modo que corresponda.

   Formato: "[I]tipoN|texto"
     [I]   intensidad 1=suave 2=medio 3=picante.
           Si se omite, la carta hereda el `lvl` del modo.
     tipo  r=reto p=pregunta yn=yo nunca rg=regla vt=votación
           vs=duelo mm=mímica tm=contrarreloj dd=dado sh=shot
           cc=cultura chupística tr=reparte aq=agua
           pc=premio o castigo
     N     rondas (rg) o segundos (tm)
     texto {j} y {j2} se reemplazan por jugadores.
           § separa partes: pregunta§respuesta · reto§premio§castigo
   ========================================================= */

/* ---------- tipos de carta ---------- */
const TYPES={
  r:{l:'Reto'}, p:{l:'Pregunta'}, yn:{l:'Yo nunca'}, rg:{l:'Regla nueva'},
  vt:{l:'Votación'}, vs:{l:'Duelo'}, mm:{l:'Mímica'}, tm:{l:'Contrarreloj'},
  dd:{l:'Dado'}, sh:{l:'Shot'}, cc:{l:'Cultura chupística'}, tr:{l:'Reparte'},
  aq:{l:'Hidrátate 💧'}
};

/* ---------- MODOS ----------
   formato de carta: "tipo|texto"  ·  "rgN|" = regla por N rondas  ·  "tmN|" = timer N seg
   trivia: "p|pregunta§respuesta"  ·  {j} y {j2} = jugadores al azar
--------------------------------*/
const MODES=[
{id:'previa',nm:'Previa',em:'🥤',c:'#8b6cff',ds:'Para romper el hielo sin sustos.',lvl:1,deck:[
`r|{j}, imita el saludo característico de alguien del grupo. Si adivinan a quién, todos toman 1; si no, tomas 2.`,
`p|{j}, ¿cuál fue tu primera impresión de {j2}? Sé honesto y toma 1 por los nervios.`,
`yn|Yo nunca me he quedado dormido en una fiesta. Quien lo hizo, toma 2.`,
`vt|Voten: ¿quién del grupo llegaría tarde a su propia boda? El elegido toma 2.`,
`r|{j}, cuenta tu mejor dato inútil. Si a nadie le sorprende, tomas 2.`,
`cc|Marcas de bebidas. {j} empieza, sigan en ronda. El que falla o repite toma 3.`,
`rg3|Prohibido decir "sí". Quien lo diga toma 1.`,
`tr|{j}, reparte 3 sorbos entre quienes quieras.`,
`p|{j}, ¿playa o montaña? Los que opinen distinto a ti toman 1.`,
`r|Todos cambien de asiento ya. El último en sentarse toma 2.`,
`tm20|{j}, nombra 5 países que empiecen con la misma letra antes del pitido o toma 3.`,
`yn|Yo nunca he stalkeado a un ex. Quien sí, toma 2.`,
`vs|{j} vs {j2}: piedra, papel o tijera al mejor de 3. El perdedor toma 2.`,
`dd|{j}, lanza el dado y toma esa cantidad de sorbos.`,
`aq|Pausa saludable: todos toman un buen sorbo de AGUA. Tu yo de mañana lo agradece.`,
`p|{j}, ¿qué canción te pone de buen humor sí o sí? Ponla, y todos toman 1 al ritmo.`]},
{id:'locura',nm:'Locura',em:'🤪',c:'#ff3d7f',ds:'Caos puro. Nadie sale igual.',lvl:2,deck:[
`r|{j}, habla como robot hasta tu próximo turno o toma 3.`,
`r|El último en tocar algo de color rojo toma 3.`,
`rg4|{j} es "Su Majestad". Quien le hable sin decirle Majestad toma 2.`,
`tm15|Papa caliente: pasen el celular en círculo. Quien lo tenga cuando suene, toma 3.`,
`r|{j}, muéstrale a {j2} la última foto de tu galería o toma 4.`,
`vs|{j} vs {j2}: duelo de miradas. El primero en reír o parpadear toma 3.`,
`r|{j}, baila 15 segundos sin música. El grupo decide: aprobado (todos toman 1) o reprobado (tomas 3).`,
`sh|{j}, el destino te eligió: shot o cuenta tu momento más vergonzoso.`,
`tr|{j}, elige a tu socio de fechorías: cada vez que tú tomes, esa persona toma contigo por 3 rondas.`,
`r|Todos hablen en susurros hasta la próxima carta. Quien grite, toma 2.`,
`dd|{j}, lanza el dado: si sale par repartes esa cantidad, si sale impar la tomas tú.`,
`r|{j}, intercambia una prenda visible (chaqueta, gorro, lentes) con {j2} o ambos toman 2.`,
`yn|Yo nunca me he ido de una fiesta sin despedirme. Los fantasmas 👻 toman 2.`,
`mm|{j}, actúa "gallina en patineta". Si nadie adivina en 30 segundos, tomas 3.`,
`r|Grito grupal en 3, 2, 1… El más tímido toma 2.`]},
{id:'bar',nm:'Bar',em:'🍸',c:'#ffb24d',ds:'Rápidas y directas, para la salida.',lvl:1,deck:[
`r|{j}, brinda con un discurso de 10 segundos por algo absurdo. Todos toman 1.`,
`vt|Voten: ¿quién sobreviviría menos a una noche sin celular? Toma 2.`,
`r|{j}, cuenta un chiste ya. Si nadie ríe, tomas 2.`,
`cc|Cócteles o tragos. {j} arranca. El que repite o falla toma 3.`,
`p|{j}, ¿cuál es tu "pedido de siempre"? Quien pediría lo mismo toma 1 contigo.`,
`r|El último en chocar su vaso con todos toma 2.`,
`tm20|{j}, nombra 6 bares, antros o discos antes del pitido o toma 3.`,
`yn|Yo nunca he fingido conocer una canción en el karaoke. Toma 2.`,
`vs|{j} vs {j2}: quién aguanta más sin usar las manos para nada. El primero en usarlas toma 2.`,
`rg3|Solo se puede beber con la mano menos hábil. Infractores toman 1 extra.`,
`tr|{j}, invita 2 sorbos a la persona mejor vestida del grupo.`,
`r|{j}, logra que alguien te diga "salud" sin pedirlo directamente, o toma 2.`,
`dd|{j}, dado al aire: del 1 al 3 tomas tú, del 4 al 6 eliges quién.`,
`aq|Ronda de agua para todo el bar. Hidratarse también es de valientes.`]},
{id:'coqueto',nm:'Coqueto',em:'😏',c:'#ff6ea9',ds:'Sube la temperatura… con estilo.',lvl:2,deck:[
`p|{j}, ¿cuál es tu "green flag" favorita en una persona? Quien la tenga, toma 1 con orgullo.`,
`r|{j}, lánzale tu mejor piropo (respetuoso) a {j2}. Si se sonroja, toma 1; si no, tomas tú 2.`,
`yn|Yo nunca he mandado un mensaje coqueto que quedó en visto. F. Toma 2.`,
`vt|Voten: ¿quién tiene la mejor sonrisa del grupo? El ganador reparte 3 sorbos.`,
`rg2|{j}, guiña un ojo a {j2} cada vez que {j2} hable.`,
`p|{j}, describe tu cita ideal en 10 palabras exactas o toma 2.`,
`vs|{j} vs {j2}: duelo de miradas intensas estilo telenovela. Quien ría primero toma 2.`,
`r|{j}, di el nombre de {j2} con tu voz más seductora. Si el jurado da menos de 7/10, tomas 2.`,
`yn|Yo nunca he ensayado una conversación antes de tenerla. Toma 1, estratega.`,
`p|{j}, tu primer beso: ¿historia romántica o desastre? Cuéntala o toma 3.`,
`rg3|Prohibido decir "amor", "lindo", "linda" o "bebé". Toma 1 por infracción.`,
`r|{j}, envía un "hola 😏" a tu último match o crush… o toma 3 y guarda el misterio.`,
`tr|{j}, regala 2 sorbos a quien te caiga mejor hoy. Sin explicaciones.`,
`p|{j}, ¿qué canción le dedicarías a alguien presente? No digas a quién. Todos toman 1 de intriga.`]},
{id:'trivia',nm:'Trivia',em:'🧠',c:'#59c2ff',ds:'Fallas, tomas. Simple.',lvl:1,deck:[
`p|¿Cuál es el río más largo del mundo?§El Amazonas, según las mediciones más recientes (el Nilo pelea el título). Si fallaste, toma 2.`,
`p|¿En qué año llegó el ser humano a la Luna?§1969. Fallo = 2 sorbos.`,
`p|¿Cuántos corazones tiene un pulpo?§Tres. Fallo = 2 sorbos.`,
`p|¿Cuál es la capital de Australia?§Canberra (no, no es Sídney). Fallo = 2 sorbos.`,
`p|¿Qué planeta es el más caliente del sistema solar?§Venus. Fallo = 2 sorbos.`,
`p|¿Cuántos huesos tiene el cuerpo humano adulto?§206. Fallo = 2 sorbos.`,
`p|¿Quién pintó "La noche estrellada"?§Vincent van Gogh. Fallo = 2 sorbos.`,
`p|¿Cuál es el país más poblado del mundo?§India (superó a China en 2023). Fallo = 2 sorbos.`,
`p|¿Cuál es el animal más rápido del planeta?§El halcón peregrino, en picada. Fallo = 2 sorbos.`,
`p|¿Cuántos minutos tiene un día completo?§1.440 minutos. Fallo = 2 sorbos.`,
`p|¿Cuál es el idioma con más hablantes nativos?§El chino mandarín. Fallo = 2 sorbos.`,
`p|¿Qué gas es el más abundante en el aire que respiramos?§El nitrógeno (~78%). Fallo = 2 sorbos.`,
`p|¿Cuántas cuerdas tiene una guitarra clásica?§Seis. Fallo = 2 sorbos.`,
`p|¿En qué continente está Egipto?§África (aunque el Sinaí es Asia, tramposos). Fallo = 2 sorbos.`]},
{id:'parejas',nm:'Parejas',em:'💘',c:'#ff5470',ds:'Para dos. Modo cita.',min:2,lvl:2,deck:[
`p|{j}, ¿qué fue lo primero que te atrajo de {j2}? Con detalles o tomas 2.`,
`r|Mírense a los ojos 30 segundos sin hablar. Quien ría primero toma 2.`,
`p|{j}, ¿cuál ha sido su mejor cita hasta ahora y por qué?`,
`r|{j}, dale un beso a {j2} donde tú elijas (con respeto 😌) o ambos toman 1.`,
`yn|Yo nunca he revisado el horóscopo de mi pareja. Quien sí, toma 1.`,
`p|{j2}, ¿qué manía tuya crees que {j} tolera con amor? Si aciertas, ambos toman 1 de premio.`,
`r|Planeen en 60 segundos su próxima escapada soñada. Si no se ponen de acuerdo, ambos toman 2.`,
`p|{j}, ¿qué canción es "la de ustedes"? Si no coinciden, ambos toman 2.`,
`r|{j}, imita a {j2} en una discusión típica. Si {j2} se ríe, toma 2; si se ofende, tomas tú 2.`,
`p|{j2}, di 3 cosas que admiras de {j}. Si dices menos de 3, tomas 3.`,
`r|Abrazo de 10 segundos, obligatorio y sin quejas. Después ambos toman 1 por cursis.`,
`p|{j}, ¿qué aprendiste de tu peor relación pasada? Comparte o toma 2.`,
`vs|Duelo: ¿quién conoce mejor al otro? Cada uno hace una pregunta; quien falle toma 2.`,
`tr|{j}, decide: ambos toman 2 juntos, o nadie toma y se deben un favor.`]},
{id:'after',nm:'After',em:'🌙',c:'#c084fc',ds:'Solo para valientes de madrugada.',lvl:3,deck:[
`sh|{j}, es tarde para arrepentirse: shot o confiesa a qué hora querías irte en realidad.`,
`p|{j}, ¿cuál es el mensaje del que más te arrepientes haber enviado? Cuenta o toma 4.`,
`yn|Yo nunca he llorado en una fiesta. Los sensibles toman 2, con orgullo.`,
`r|{j}, llama a tu mejor amigo que no está aquí y dile que lo quieres. O toma 4.`,
`vt|Voten: ¿quién está más cerca de quedarse dormido? Toma 3 para despertar.`,
`r|{j}: {j2} dice un número al azar y tú muestras esa foto de tu galería, o tomas 4.`,
`p|{j}, ¿qué harías si supieras que nadie te va a juzgar? Responde o toma 3.`,
`rg4|Modo confesionario: quien haga una pregunta debe responderla también. Infracción: 2 sorbos.`,
`sh|Quien no haya dicho nada vergonzoso hoy, toma un shot… o confiesa algo ya.`,
`r|{j}, intercambia celulares (bloqueados 😉) con {j2} por una ronda. Quien se niegue toma 3.`,
`yn|Yo nunca he dicho "esta es la última" y pedí otra. Todos sabemos quiénes son: toman 3.`,
`p|{j}, ¿a quién del grupo le confiarías un secreto grave? Señálalo; esa persona toma 1 de honor.`,
`tm25|{j}, convence al grupo de por qué la noche NO debe terminar. Si no aplauden, tomas 3.`,
`aq|Check de realidad: agua para todos. La mejor decisión de la noche.`,
`tr|{j}, reparte 5 sorbos. Con gran poder viene gran resaca.`]},
{id:'mimica',nm:'Mímica',em:'🎭',c:'#ffd166',ds:'Actúa sin hablar. 30 seg: si no adivinan, el actor toma 3; si adivinan, el resto toma 1.',lvl:1,deck:[
`mm|{j}, actúa: influencer grabando un unboxing.`,
`mm|{j}, actúa: gato que tiró un vaso y no se arrepiente.`,
`mm|{j}, actúa: persona buscando señal de wifi en medio del campo.`,
`mm|{j}, actúa: abuela aprendiendo a usar TikTok.`,
`mm|{j}, actúa: superhéroe con dolor de espalda.`,
`mm|{j}, actúa: cajero de supermercado un lunes a primera hora.`,
`mm|{j}, actúa: turista perdido preguntando direcciones.`,
`mm|{j}, actúa: chef furioso probando una sopa horrible.`,
`mm|{j}, actúa: fan conociendo a su ídolo.`,
`mm|{j}, actúa: robot bailando reguetón.`,
`mm|{j}, actúa: profesor de yoga estresado.`,
`mm|{j}, actúa: vampiro vegetariano.`,
`mm|{j}, actúa: árbitro cobrando penal en la final.`,
`mm|{j}, actúa: persona que pisó una pieza de Lego descalza.`]},
{id:'hot',nm:'Hot',em:'🔥',c:'#ff2e63',ds:'Picante, confesional y con 👀.',lvl:3,deck:[
`p|{j}, ¿cuál es tu tipo? Descríbelo sin mirar a nadie… o mirando 👀. Toma 1 al terminar.`,
`yn|Yo nunca he tenido un sueño subido de tono con alguien de este grupo. Quien tome, no dice con quién 🤐.`,
`r|{j}, susurra algo al oído de {j2}. Si {j2} se ríe o sonroja, toma 2; si queda de piedra, tomas tú 2.`,
`vt|Voten: ¿quién es más coqueto sin darse cuenta? Toma 3.`,
`p|{j}, tu beso más memorable: ¿dónde fue? Ciudad y contexto, sin nombres. O toma 3.`,
`r|{j}, baila algo sensual 10 segundos o toma 3. El grupo aplaude sí o sí.`,
`yn|Yo nunca he vuelto con un ex sabiendo que era mala idea. Toma 3, campeón.`,
`p|{j}, del 1 al 10, ¿qué tan bien besas según tú? El grupo vota si te cree. Si no, tomas 2.`,
`r|{j} y {j2}: recreen la pose de portada de una novela romántica. Quien se niegue toma 3.`,
`p|{j}, ¿qué es más atractivo: inteligencia, humor o físico? Los que discrepen toman 1.`,
`rg3|Prohibido decir la palabra "sexy". Infracción: 2 sorbos.`,
`sh|{j}, shot o verdad: ¿te gusta alguien en este momento? Con sí o no basta.`,
`tr|{j}, regala 3 sorbos a la persona más guapa del grupo. Sin empates.`,
`yn|Yo nunca he coqueteado para conseguir algo gratis. Toma 2, estratega.`]},
{id:'conflicto',nm:'Conflicto',em:'⚡',c:'#ff8c42',ds:'Votaciones incómodas. Sin llorar.',lvl:2,deck:[
`vt|Voten: ¿quién deja en visto con más frialdad? Toma 3.`,
`vt|Voten: ¿quién es más probable que olvide tu cumpleaños? Toma 2.`,
`vs|{j} vs {j2}: debate de 30 segundos. Tema: "el reguetón es cultura". {j} a favor, {j2} en contra. El grupo elige perdedor: toma 3.`,
`vt|Voten: ¿quién pide "un poquito" de tu comida y se come la mitad? Toma 3.`,
`p|{j}, di algo que el grupo hace y te molesta en secreto. Si confiesas, toma 1 por valiente; si no, toma 3.`,
`vt|Voten: ¿quién tarda más en arreglarse? Toma 2.`,
`vs|{j} vs {j2}: brazo extendido sosteniendo el vaso. El que lo baje primero toma 3.`,
`vt|Voten: ¿quién es más terco? Los dos más votados toman 2 cada uno.`,
`p|{j}, sinceridad: ¿quién del grupo vive pegado al celular en las juntas? Esa persona toma 2.`,
`vt|Voten: ¿quién cancela planes a última hora? Toma 3 y promete cambiar (mentira).`,
`vs|{j} vs {j2}: guerra de cumplidos pasivo-agresivos. El grupo corona al más filoso; el otro toma 2.`,
`vt|Voten: ¿quién manda audios de 3 minutos? Toma 3.`,
`rg3|Prohibido defenderse de las votaciones. Quejarse = 1 sorbo extra.`,
`vt|Voten: ¿quién ganaría una discusión sin tener razón? Toma 3 como trofeo.`]},
{id:'muerte',nm:'Muerte súbita',em:'💀',c:'#f43f5e',ds:'Retos relámpago. Fallar cuesta caro.',lvl:2,deck:[
`tm10|{j}, di 3 nombres del grupo en orden alfabético. Falla = 3 sorbos.`,
`tm10|{j}, cuenta del 20 al 1 al revés sin tropezar. Falla = 3 sorbos.`,
`vs|{j} vs {j2}: par o impar con los dedos, a una. Perdedor: 3 sorbos.`,
`tm10|{j}, nombra 4 colores en inglés. Falla = 3.`,
`cc|Ronda relámpago: animales de granja. Quien dude 3 segundos toma 3.`,
`tm10|{j}, deletrea MURCIÉLAGO sin equivocarte. Falla = 3.`,
`vs|{j} vs {j2}: "tres tristes tigres" a máxima velocidad. El grupo decide; perdedor toma 3.`,
`tm10|{j}, di 5 frutas que no sean rojas. Falla = 3.`,
`dd|{j}, dado de la muerte: con 1 o 6 estás a salvo; cualquier otro número, tómalo en sorbos.`,
`tm10|{j}, repite exacto el ritmo de aplausos que invente {j2}. Falla = 3.`,
`vs|{j} vs {j2}: piedra, papel o tijera a UNA ronda (empate se repite). Perdedor toma 3.`,
`tm10|{j}, nombra 3 películas con números en el título. Falla = 3.`]},
{id:'noventas',nm:"90's",em:'📼',c:'#22d3ee',ds:'Nostalgia pura para millennials.',lvl:1,deck:[
`r|{j}, tararea un tono de celular clásico de los 2000. Si nadie lo reconoce, tomas 2.`,
`p|{j}, ¿VHS o DVD marcó tu infancia? Los del otro bando toman 1.`,
`yn|Yo nunca he soplado un cartucho de videojuego. Los que sí, toman 1 con nostalgia.`,
`cc|Caricaturas de los 90 y 2000. {j} empieza. Falla = 3.`,
`r|{j}, baila la coreografía de alguna canción noventera 10 segundos o toma 2.`,
`p|{j}, ¿cuál era tu programa de TV favorito de niño? Si alguien más lo veía, toman 1 juntos.`,
`yn|Yo nunca quemé un CD con música descargada. Toma 2, pirata retro.`,
`mm|{j}, actúa: "esperar a que cargue una página con internet por teléfono". Si adivinan, todos toman 1; si no, tomas 2.`,
`r|{j}, di "hola como estas" letra por letra como si escribieras en un teclado T9. Si te aburres, 2 sorbos.`,
`vt|Voten: ¿quién tiene el alma más noventera? Toma 2 con honor.`,
`p|{j}, ¿walkman, discman o mp3: cuál usaste primero? Quienes no usaron ninguno toman 1 por jóvenes.`,
`tm20|{j}, nombra 5 juguetes clásicos antes del pitido o toma 3.`,
`yn|Yo nunca he llorado con una película animada. Quien no tome está mintiendo 😏.`]},
{id:'nunca',nm:'Nunca nunca',em:'🙊',c:'#a78bfa',ds:'Quien SÍ lo hizo toma 2. Sin excusas.',lvl:2,deck:[
`yn|Yo nunca me he hecho el dormido para no hablar con alguien.`,
`yn|Yo nunca he olvidado el nombre de alguien mientras lo presentaba.`,
`yn|Yo nunca he respondido "jajaja" sin reírme ni un poco.`,
`yn|Yo nunca he entrado a una reunión online sin pantalones formales.`,
`yn|Yo nunca he fingido una llamada para escapar de una conversación.`,
`yn|Yo nunca he comido algo del piso invocando la regla de los 5 segundos.`,
`yn|Yo nunca he dicho "ya voy en camino" estando en pijama.`,
`yn|Yo nunca he stalkeado al ex de mi ex.`,
`yn|Yo nunca me he reído en un momento totalmente inapropiado.`,
`yn|Yo nunca he cantado en la ducha como si fuera un concierto.`,
`yn|Yo nunca he devuelto un "te quiero" sin sentirlo del todo.`,
`yn|Yo nunca he mentido en este juego. (Quien tome aquí, toma doble 😈).`,
`yn|Yo nunca he llorado por una serie.`,
`yn|Yo nunca he usado la misma excusa dos veces con la misma persona.`,
`yn|Yo nunca he revisado el celular de alguien sin permiso.`]},
{id:'shot',nm:'Shot',em:'🥃',c:'#fb7185',ds:'Todo shot se puede cambiar por 3 sorbos. Nadie está obligado.',lvl:2,deck:[
`sh|{j}, shot o karaoke: canta 20 segundos de la canción que elija el grupo.`,
`sh|{j} y {j2}: shot en espejo. Uno guía los movimientos, el otro imita. O ambos toman 2 y paz.`,
`sh|{j}, shot o responde una verdad incómoda a elección del grupo.`,
`sh|{j}, gira una botella (o tu dedo con ojos cerrados). El señalado: shot o 3 sorbos.`,
`sh|{j}, brinda un shot con la persona que menos conoces del grupo… o cuéntale un secreto leve.`,
`sh|{j}, shot o 10 sentadillas ahora mismo.`,
`sh|El último que llegó hoy: shot de bienvenida tardía o 3 sorbos.`,
`sh|{j}, prepara un "shot misterioso" solo con cosas comestibles y seguras. {j2} lo prueba o toma 3.`,
`sh|{j}, shot o imita a un famoso hasta que alguien adivine.`,
`sh|Shot comunitario: todos los que tengan menos de 20% de batería.`,
`aq|Intermedio obligatorio: vaso de agua antes del próximo shot. En serio.`,
`sh|{j}, shot o deja que el grupo elija tu foto de perfil por 24 horas.`,
`sh|{j}, shot o baila 15 segundos sin música con toda la seriedad del mundo.`]},
{id:'uni',nm:'Universidad',em:'🎓',c:'#60a5fa',ds:'Para mechones, novatos y sobrevivientes.',lvl:1,deck:[
`p|{j}, ¿tu peor excusa para no entregar un trabajo? Si es buena, todos toman 1; si es mala, tomas 2.`,
`yn|Yo nunca he estudiado TODO la noche anterior al examen. Toma 2, leyenda.`,
`r|{j}, expón 20 segundos sobre un tema que no dominas, con total confianza. Si convences, repartes 3.`,
`cc|Carreras universitarias. Falla = 3.`,
`yn|Yo nunca me he dormido en clases. Toma 2.`,
`vt|Voten: ¿quién es el que siempre pide los apuntes? Toma 3.`,
`p|{j}, en trabajos en grupo: ¿líder, aportador o fantasma? Confiesa. Los fantasmas toman 2.`,
`r|{j}, defiende esta tesis 20 segundos: "las tareas para la casa deberían ser ilegales". Sin risas del público, tomas 2.`,
`yn|Yo nunca he ido a clases solo por la asistencia. Toma 1.`,
`tm15|{j}, nombra 5 ramos o materias que hayas odiado. Rápido o toma 2.`,
`vs|{j} vs {j2}: ¿cuánto es 7 × 8 + 4? El más lento toma 2.`,
`rg3|Todos deben llamarse "colega" entre sí. Olvido = 1 sorbo.`,
`p|{j}, ¿qué le dirías a tu yo de primer año? Todos brindan 1 por eso.`]},
{id:'fit',nm:'Fit',em:'💪',c:'#34d399',ds:'Retos físicos. Sudar o tomar.',lvl:1,deck:[
`r|{j}, 10 sentadillas o toma 3. El grupo cuenta en voz alta.`,
`r|Plancha grupal 20 segundos. Quien caiga primero toma 2.`,
`vs|{j} vs {j2}: quién aguanta más en cuclillas contra la pared. Perdedor toma 3.`,
`r|{j}, 15 jumping jacks con sonrisa obligatoria o toma 2.`,
`tm30|Todos en equilibrio sobre un pie hasta el pitido. Quien toque el piso toma 2.`,
`r|{j}, tócate la punta de los pies sin doblar rodillas. ¿Llegas? Repartes 2. ¿No? Tomas 2.`,
`vs|{j} vs {j2}: guerra de pulgares al mejor de 3. Perdedor toma 2.`,
`r|{j}, 5 flexiones estilo libre (con rodillas vale). O toma 3.`,
`r|{j}, camina en cámara lenta exagerada de un extremo al otro. Si {j2} (el jurado) no aprueba, tomas 2.`,
`tm20|{j}, trota en el lugar hasta el pitido con ánimo de final olímpica. Rendirse = 3 sorbos.`,
`r|{j}, sostén tu vaso con el brazo extendido 30 segundos. Si tiembla mucho (decide el grupo), toma 2.`,
`r|Sesión de estiramiento de 20 segundos dirigida por {j}. Quien no participe toma 2.`]},
{id:'versus',nm:'Versus',em:'⚔️',c:'#f59e0b',ds:'Duelos 1 vs 1. Solo puede quedar uno.',lvl:2,deck:[
`vs|{j} vs {j2}: quién nombra más capitales por turnos en 20 segundos. Perdedor toma 3.`,
`vs|{j} vs {j2}: duelo de talentos ocultos de 15 segundos. El grupo vota; perdedor toma 3.`,
`vs|{j} vs {j2}: guerra de pulgares al mejor de 3. Perdedor toma 2.`,
`vs|{j} vs {j2}: sonrisa falsa sostenida mientras el grupo intenta hacerlos reír de verdad. Perdedor toma 2.`,
`vs|{j} vs {j2}: deletreen OTORRINOLARINGÓLOGO. El más rápido y correcto gana; perdedor toma 3.`,
`vs|{j} vs {j2}: batalla de baile de 15 segundos. Perdedor toma 3, ganador reparte 2.`,
`vs|{j} vs {j2}: el grupo piensa un número del 1 al 10 en secreto. Quien diga el más lejano toma 2.`,
`vs|{j} vs {j2}: piedra, papel o tijera a 5 rondas relámpago. Perdedor toma 3.`,
`vs|{j} vs {j2}: imiten un animal que elija el grupo. El menos convincente toma 2.`,
`vs|{j} vs {j2}: digan el abecedario alternando letras y mirándose fijo. El que se equivoque toma 3.`,
`vs|{j} vs {j2}: quién dice más palabras que empiecen con TR en 15 segundos. Perdedor toma 2.`,
`vs|{j} vs {j2}: duelo de datos inútiles, uno cada uno hasta que alguien se quede sin. Perdedor toma 3.`,
`vs|{j} vs {j2}: quién hace reír primero al otro solo con gestos. Perdedor toma 2.`]},
{id:'invierno',nm:'Invierno',em:'❄️',c:'#7dd3fc',ds:'Team frazada, este es su momento.',season:true,lvl:1,deck:[
`p|{j}, ¿tu plan perfecto de invierno: película, comida y compañía? Descríbelo o toma 2.`,
`r|{j}, abraza a {j2} tipo "pingüino en tormenta" por 5 segundos. Ambos toman 1 de calorcito.`,
`yn|Yo nunca me he negado a salir por frío. Toma 2, team frazada.`,
`cc|Cosas calientes: bebidas, comidas o lugares. Falla = 3.`,
`r|{j}, imita a alguien entrando al mar helado. Si el grupo tirita contigo, repartes 2.`,
`vt|Voten: ¿quién es más friolento? Toma 2 bien abrigado.`,
`p|{j}, ¿chocolate caliente, café o té? Tu bando toma 1 unido.`,
`tm15|{j}, nombra 4 deportes de invierno o toma 2.`,
`r|El último en ponerse algo extra "de abrigo" (real o improvisado) toma 2.`,
`yn|Yo nunca he dormido con calcetines. Los polares toman 1.`,
`mm|{j}, actúa: muñeco de nieve derritiéndose. Adivinan = todos toman 1; no = tomas 2.`,
`p|{j}, cuenta tu mejor recuerdo de unas vacaciones de invierno o toma 2.`]},
{id:'navidad',nm:'Navidad',em:'🎄',c:'#ef4444',ds:'Ho ho ho con sorbos.',season:true,lvl:1,deck:[
`p|{j}, ¿el regalo más raro que has recibido? Cuéntalo o toma 2.`,
`r|{j}, canta 10 segundos de un villancico con estilo de rockstar o toma 2.`,
`yn|Yo nunca he reciclado un regalo. Toma 2, gestor eficiente.`,
`vt|Voten: ¿quién compra los regalos el 24 a última hora? Toma 3.`,
`cc|Comidas típicas de fin de año. Falla = 3.`,
`r|{j}, da un discurso navideño de 15 segundos que incluya la palabra "renos". Todos toman 1 al final.`,
`mm|{j}, actúa: Papá Noel atascado en la chimenea. Adivinan = repartes 2; no = tomas 2.`,
`p|{j}, ¿cena ideal: familiar tranquila o fiesta total? Tu bando toma 1.`,
`yn|Yo nunca he llorado con una película navideña. Toma 1, corazón de pan de pascua.`,
`r|Todos digan "¡salud y feliz navidad!" al unísono. Quien se adelante o atrase toma 1.`,
`tr|{j}, haz de Viejito Pascuero: reparte 4 sorbos entre quienes se "portaron mal" este año.`,
`p|{j}, un propósito de año nuevo que NO cumpliste. Confiesa o toma 3.`]}
];

/* ---------- especiales ---------- */
const SPECIALS=[
{id:'rey',nm:'Cuarto rey',em:'👑',c:'#eab308',ds:'La baraja clásica, versión digital.'},
{id:'impostor',nm:'Impostor',em:'🕵️',c:'#94a3b8',ds:'Uno miente. Encuéntrenlo.',min:3},
{id:'ruleta',nm:'Ruleta',em:'🎡',c:'#e879f9',ds:'Gira y que decida el destino.'}
];

const KING_RULES={
'A':`¡Cascada! Todos empiezan a tomar a la vez; nadie puede parar hasta que pare quien tiene a su derecha.`,
'2':`Tú das: elige quién toma 2.`,
'3':`Para ti: tomas 3.`,
'4':`Al suelo: el último en tocar el piso toma 2.`,
'5':`Chicos: los hombres toman 2. Si no hay, todos toman 1.`,
'6':`Chicas: las mujeres toman 2. Si no hay, todos toman 1.`,
'7':`Al cielo: el último en levantar la mano toma 2.`,
'8':`Tu pareja: elige a alguien; cuando tú tomes, esa persona toma contigo hasta el próximo 8.`,
'9':`Rima: di una palabra; en ronda, cada uno dice una que rime. Quien falle toma 3.`,
'10':`Categorías: elige un tema; en ronda, cada uno dice un ejemplo. Quien falle toma 3.`,
'J':`Regla del rey: inventa una regla para lo que queda de juego. Romperla cuesta 2 sorbos.`,
'Q':`Reina preguntona: hazle una pregunta a alguien; esa persona pregunta a otra, y así. Quien responda o dude, toma 2.`,
'K':`¡Rey! Sirve un poco de tu bebida al Vaso del Rey.`};
const KING_LAST=`👑 ¡CUARTO REY! Te toca el Vaso del Rey. Tómalo… o cámbialo por 5 sorbos y una reverencia.`;

const IMP_WORDS={
'Comida':['pizza','sushi','empanada','tacos','ramen','asado'],
'Lugares':['playa','aeropuerto','gimnasio','cine','hospital','biblioteca'],
'Animales':['pingüino','tiburón','perezoso','camello','búho','pulpo'],
'Fiesta':['karaoke','piñata','brindis','DJ','confeti','previa'],
'Objetos':['paraguas','linterna','mochila','espejo','almohada','control remoto'],
'Profesiones':['dentista','bombero','chef','astronauta','profesor','taxista'],
'Pantalla':['terror','comedia romántica','documental','anime','telenovela','superhéroes'],
'Deportes':['fútbol','natación','ajedrez','boxeo','tenis','escalada']};

const WHEEL_DARES=[`toma 2 sorbos`,`reparte 3 sorbos`,`cuenta un chiste o toma 2`,`elige quién toma 2`,`todos toman 1 menos tú`,`imita a alguien del grupo`,`di un cumplido a cada persona`,`toma 1 y gira de nuevo`,`inventa una regla por 2 rondas`,`te salvaste: nada esta vez`];

/* ---------- export para los tests (en el navegador esto se ignora) ---------- */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TYPES, MODES, SPECIALS, KING_RULES, KING_LAST, IMP_WORDS, WHEEL_DARES };
}
